/*
l4_shim.c — the C boundary between JavaScript and the Lean-compiled code.

This file is NOT a place for RDF or SPARQL logic. It does exactly three
things, and any change that adds a fourth belongs in Lean instead:

  1. runs the Lean module initialisers once;
  2. converts `char *` <-> Lean string objects;
  3. hands JavaScript a plain `char *` it can read out of the wasm heap.

MEMORY OWNERSHIP — the rules a caller must follow.

  * Lean's calling convention for `@[export]`ed functions is OWNED
    arguments: the callee consumes each `lean_object *` passed to it, so
    the shim must NOT `lean_dec` an argument it has already handed over.
  * The `lean_object *` a Lean function returns is owned by the caller;
    the shim copies its bytes out with `strdup` and then `lean_dec`s it.
  * The `char *` returned to JavaScript is malloc'd HERE and is owned by
    JAVASCRIPT. The caller must pass it back to `l4_free_result` exactly
    once. Every wrapper in l4factoidal.js does this in a `finally`.
  * Returned strings are NUL-terminated UTF-8. Lean strings may contain
    no interior NUL, so a NUL-terminated read is lossless.

A NULL return means the allocation failed; it is not a Lean-level error.
Lean-level errors come back as a JSON document with an "error" key, so
the boundary itself never has to carry an exception.
*/
#include <lean/lean.h>
#include <stdlib.h>
#include <string.h>

#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#define L4_EXPORT EMSCRIPTEN_KEEPALIVE
#else
#define L4_EXPORT
#endif

/* Declared in the runtime's C++ headers, not in lean.h; Lean's own
   generated `main` declares them the same way. */
void lean_initialize_runtime_module(void);
void lean_io_mark_end_initialization(void);

/* Generated by the Lean compiler from Wasm/Exports.lean. */
extern lean_object *l4_version(lean_object *unit);
extern lean_object *l4_bgp_query(lean_object *data_json, lean_object *bgp_json);
extern lean_object *l4_call(lean_object *op, lean_object *args_json);

/* Module initialiser for Wasm.Exports; it chains through every import,
   Init included. Name pattern: initialize_<package>_<Module_Path>. */
extern lean_object *initialize_l4factoidal_Wasm_Exports(uint8_t builtin);

static int g_l4_initialized = 0;

/* Idempotent. Safe to call before every entry point. */
static int l4_ensure_init(void) {
    if (g_l4_initialized) return 1;
    lean_initialize_runtime_module();
    lean_object *res = initialize_l4factoidal_Wasm_Exports(1 /* builtin */);
    if (!lean_io_result_is_ok(res)) {
        lean_io_result_show_error(res);
        lean_dec(res);
        return 0;
    }
    lean_dec_ref(res);
    lean_io_mark_end_initialization();
    g_l4_initialized = 1;
    return 1;
}

/* Copy a Lean string's bytes into a malloc'd buffer and release the
   Lean object. Consumes `s`. */
static char *l4_take_string(lean_object *s) {
    const char *c = lean_string_cstr(s);
    char *out = strdup(c);
    lean_dec(s);
    return out;
}

/* Explicit initialisation, so a caller can pay the cost up front and
   time it separately from the first query. Returns 1 on success. */
L4_EXPORT int l4_init(void) { return l4_ensure_init(); }

/* Returns a malloc'd UTF-8 string; free with l4_free_result. */
L4_EXPORT char *l4_version_c(void) {
    if (!l4_ensure_init()) return NULL;
    return l4_take_string(l4_version(lean_box(0)));
}

/* Returns a malloc'd UTF-8 SPARQL Query Results JSON document (or a
   JSON document with an "error" key); free with l4_free_result. */
L4_EXPORT char *l4_bgp_query_c(const char *data_json, const char *bgp_json) {
    if (!l4_ensure_init()) return NULL;
    /* lean_mk_string copies; the two objects are consumed by the call. */
    lean_object *d = lean_mk_string(data_json);
    lean_object *b = lean_mk_string(bgp_json);
    return l4_take_string(l4_bgp_query(d, b));
}

/* Returns a malloc'd UTF-8 JSON envelope ({"ok":true,...} or
   {"ok":false,"error":"..."}); free with l4_free_result. `op` is the
   method name, `args_json` a JSON array of strings (positional
   arguments) -- see Wasm/Dispatch.lean. */
L4_EXPORT char *l4_call_c(const char *op, const char *args_json) {
    if (!l4_ensure_init()) return NULL;
    /* lean_mk_string copies; the two objects are consumed by the call. */
    lean_object *o = lean_mk_string(op);
    lean_object *a = lean_mk_string(args_json);
    return l4_take_string(l4_call(o, a));
}

/* Release a buffer returned by l4_version_c / l4_bgp_query_c /
   l4_call_c. */
L4_EXPORT void l4_free_result(char *p) { free(p); }
