/*
l4_shim.c — the C boundary between JavaScript and the Lean-compiled code.

This file is NOT a place for RDF or SPARQL logic. It does exactly three
things, and any change that adds a fourth belongs in Lean instead:

  1. runs the Lean module initialisers once;
  2. converts `char *` <-> Lean string objects;
  3. hands JavaScript a plain `char *` it can read out of the wasm heap.

MEMORY OWNERSHIP — the rules a caller must follow.

  * Lean's calling convention for `@[export]`ed functions is OWNED
    arguments: the callee consumes each `lean_object *` passed to it, so
    the shim must NOT `lean_dec` an argument it has already handed over.
  * The `lean_object *` a Lean function returns is owned by the caller;
    the shim copies its bytes out with `strdup` and then `lean_dec`s it.
  * The `char *` returned to JavaScript is malloc'd HERE and is owned by
    JAVASCRIPT. The caller must pass it back to `l4_free_result` exactly
    once. Every wrapper in l4factoidal.js does this in a `finally`.
  * Returned strings are NUL-terminated UTF-8. Lean strings may contain
    no interior NUL, so a NUL-terminated read is lossless.

A NULL return means the allocation failed; it is not a Lean-level error.
Lean-level errors come back as a JSON document with an "error" key, so
the boundary itself never has to carry an exception.
*/
#include <lean/lean.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#define L4_EXPORT EMSCRIPTEN_KEEPALIVE
#else
#define L4_EXPORT
#endif

/* Declared in the runtime's C++ headers, not in lean.h; Lean's own
   generated `main` declares them the same way. */
void lean_initialize_runtime_module(void);
void lean_io_mark_end_initialization(void);

/* Generated by the Lean compiler from Wasm/Exports.lean.

   `l4_call` (pure) remains exported for direct binders; the shim
   routes `l4_call_c` through `l4_call_io` instead, so the wire entry
   also reaches the dataset-handle ops (issue #585) whose store only
   the IO entry can touch. `l4_call_io` is an `IO String` export: the
   v4.33 code generator ERASES the IO world token (checked in the
   generated Wasm/Exports.c -- two lean_object* arguments, same as
   l4_call), and the result is an IO RESULT object wrapping the string
   (tag 0 = ok), not the string itself; unwrap it with
   lean_io_result_take_value. */
extern lean_object *l4_version(lean_object *unit);
extern lean_object *l4_bgp_query(lean_object *data_json, lean_object *bgp_json);
extern lean_object *l4_call(lean_object *op, lean_object *args_json);
extern lean_object *l4_call_io(lean_object *op, lean_object *args_json);
extern lean_object *l4_call_blob(lean_object *op, lean_object *args_json,
                                 lean_object *blob);
/* `l4_call_blob_io` is an `IO (String x ByteArray)` export. The v4.33
   code generator erases the IO world token here too (checked in the
   generated Wasm/Exports.c -- THREE lean_object* arguments, the same as
   l4_call_blob), and the result is an IO RESULT object (tag 0 = ok).
   Its value is a PAIR object, so the shim takes the value with
   lean_io_result_take_value and then reads field 0 (the Lean string)
   and field 1 (the ByteArray) with lean_ctor_get. */
extern lean_object *l4_call_blob_io(lean_object *op, lean_object *args_json,
                                    lean_object *blob);

/* Module initialiser for Wasm.Exports; it chains through every import,
   Init included. Name pattern: initialize_<package>_<Module_Path>. */
extern lean_object *initialize_l4factoidal_Wasm_Exports(uint8_t builtin);

static int g_l4_initialized = 0;

/* Idempotent. Safe to call before every entry point. */
static int l4_ensure_init(void) {
    if (g_l4_initialized) return 1;
    lean_initialize_runtime_module();
    lean_object *res = initialize_l4factoidal_Wasm_Exports(1 /* builtin */);
    if (!lean_io_result_is_ok(res)) {
        lean_io_result_show_error(res);
        lean_dec(res);
        return 0;
    }
    lean_dec_ref(res);
    lean_io_mark_end_initialization();
    g_l4_initialized = 1;
    return 1;
}

/* Copy a Lean string's bytes into a malloc'd buffer and release the
   Lean object. Consumes `s`. */
static char *l4_take_string(lean_object *s) {
    const char *c = lean_string_cstr(s);
    char *out = strdup(c);
    lean_dec(s);
    return out;
}

/* Explicit initialisation, so a caller can pay the cost up front and
   time it separately from the first query. Returns 1 on success. */
L4_EXPORT int l4_init(void) { return l4_ensure_init(); }

/* Returns a malloc'd UTF-8 string; free with l4_free_result. */
L4_EXPORT char *l4_version_c(void) {
    if (!l4_ensure_init()) return NULL;
    return l4_take_string(l4_version(lean_box(0)));
}

/* Returns a malloc'd UTF-8 SPARQL Query Results JSON document (or a
   JSON document with an "error" key); free with l4_free_result. */
L4_EXPORT char *l4_bgp_query_c(const char *data_json, const char *bgp_json) {
    if (!l4_ensure_init()) return NULL;
    /* lean_mk_string copies; the two objects are consumed by the call. */
    lean_object *d = lean_mk_string(data_json);
    lean_object *b = lean_mk_string(bgp_json);
    return l4_take_string(l4_bgp_query(d, b));
}

/* Returns a malloc'd UTF-8 JSON envelope ({"ok":true,...} or
   {"ok":false,"error":"..."}); free with l4_free_result. `op` is the
   method name, `args_json` a JSON array of strings (positional
   arguments) -- see Wasm/Dispatch.lean. Routed through `l4_call_io`
   so the dataset-handle ops (issue #585) are reachable; for every
   stateless op the envelope is byte-identical to the pure `l4_call`'s
   (Wasm/Dispatch.lean's `callIO` delegates to `call`). */
L4_EXPORT char *l4_call_c(const char *op, const char *args_json) {
    if (!l4_ensure_init()) return NULL;
    /* lean_mk_string copies; the two objects are consumed by the call. */
    lean_object *o = lean_mk_string(op);
    lean_object *a = lean_mk_string(args_json);
    lean_object *res = l4_call_io(o, a);
    if (!lean_io_result_is_ok(res)) {
        /* callIO never throws -- every failure is an {"ok":false}
           envelope -- so this branch is defensive only. */
        lean_dec(res);
        return strdup("{\"ok\":false,\"error\":\"l4_call_io returned an IO error\"}");
    }
    return l4_take_string(lean_io_result_take_value(res));
}

/* Like l4_call_c, but also carries ONE contiguous byte region.

   `blob` / `blob_len` name bytes the CALLER owns, typically written
   straight into the wasm heap with _malloc + HEAPU8.set — no encoding
   on either side. The region is copied ONCE into a Lean ByteArray
   here, so the caller may free its buffer as soon as this returns and
   Lean never holds a host pointer. Which bytes belong to which
   artifact is stated in `args_json` as {"key","offset","len"}
   descriptors, and Lean bounds-checks every window against the
   ByteArray it owns (Wasm/Ops/Store.lean).

   This function MOVES bytes and never interprets them: it contains no
   knowledge of any block, manifest or digest format. A change that
   gives it any belongs in Lean instead.

   A NULL `blob` with `blob_len` 0 is the empty region. Returns a
   malloc'd UTF-8 JSON envelope; free with l4_free_result. */
L4_EXPORT char *l4_call_blob_c(const char *op, const char *args_json,
                               const uint8_t *blob, size_t blob_len) {
    if (!l4_ensure_init()) return NULL;
    lean_object *o = lean_mk_string(op);
    lean_object *a = lean_mk_string(args_json);
    /* A ByteArray is a scalar array of 1-byte elements. */
    lean_object *b = lean_alloc_sarray(1, blob_len, blob_len);
    if (blob_len > 0 && blob != NULL) {
        memcpy(lean_sarray_cptr(b), blob, blob_len);
    }
    return l4_take_string(l4_call_blob(o, a, b));
}

/* Like l4_call_blob_c, but ALSO carries one contiguous byte region OUT.

   The ops that build an out region are named by `L4Wasm.blobIoOpNames`
   (the `ops` envelope lists them under "blobIoOps"); every other op
   answers exactly as `l4_call_c` does, with an empty out region. Bytes
   leave the module RAW: hexadecimal doubles them over the boundary, and
   base64 was refused (owner, 2026-09-03).

   MEMORY OWNERSHIP -- two buffers, two owners, two release entries.

     * The returned `char *` is the JSON envelope. It is malloc'd here
       and owned by the CALLER, exactly as for `l4_call_blob_c`. Release
       it with `l4_free_result`.
     * `*out_ptr` is the byte region. It is a SEPARATE malloc'd buffer,
       also owned by the caller, and it is released with `l4_free_blob`
       -- NOT with `l4_free_result`. The two entries are kept apart on
       purpose: the buffers hold different types, and a caller that
       mixes them is a bug that must be visible.
     * `*out_len` is the length of that region in bytes.

   On every path that returns no bytes -- an op with no out region, an
   error envelope, a failed allocation -- `*out_ptr` is NULL and
   `*out_len` is 0. A NULL return value means the envelope could not be
   allocated and is not a Lean-level error; Lean-level errors come back
   as an {"ok":false,"error":"..."} envelope.

   `out_ptr` and `out_len` must both be non-NULL. `blob` / `blob_len`
   name bytes the CALLER owns; they are copied once into a Lean
   ByteArray, as in `l4_call_blob_c`.

   This function MOVES bytes and never interprets them. */
L4_EXPORT char *l4_call_blob_io_c(const char *op, const char *args_json,
                                  const uint8_t *blob, size_t blob_len,
                                  uint8_t **out_ptr, size_t *out_len) {
    if (out_ptr == NULL || out_len == NULL) return NULL;
    *out_ptr = NULL;
    *out_len = 0;
    if (!l4_ensure_init()) return NULL;
    lean_object *o = lean_mk_string(op);
    lean_object *a = lean_mk_string(args_json);
    /* A ByteArray is a scalar array of 1-byte elements. */
    lean_object *b = lean_alloc_sarray(1, blob_len, blob_len);
    if (blob_len > 0 && blob != NULL) {
        memcpy(lean_sarray_cptr(b), blob, blob_len);
    }
    lean_object *res = l4_call_blob_io(o, a, b);
    if (!lean_io_result_is_ok(res)) {
        /* callBlobIO never throws -- every failure is an {"ok":false}
           envelope -- so this branch is defensive only. */
        lean_dec(res);
        return strdup("{\"ok\":false,\"error\":\"l4_call_blob_io returned an IO error\"}");
    }
    /* The IO value is a Prod: field 0 the envelope String, field 1 the
       ByteArray. lean_ctor_get BORROWS, so both are read while the pair
       still holds them; the pair is released afterwards. */
    lean_object *pair = lean_io_result_take_value(res);
    lean_object *env_obj = lean_ctor_get(pair, 0);
    lean_object *arr_obj = lean_ctor_get(pair, 1);
    char *envelope = strdup(lean_string_cstr(env_obj));
    size_t n = lean_sarray_size(arr_obj);
    if (envelope != NULL && n > 0) {
        uint8_t *bytes = (uint8_t *)malloc(n);
        if (bytes == NULL) {
            /* The region could not be copied out. Give the caller
               nothing rather than an envelope that promises bytes it
               did not receive. */
            free(envelope);
            lean_dec(pair);
            return NULL;
        }
        memcpy(bytes, lean_sarray_cptr(arr_obj), n);
        *out_ptr = bytes;
        *out_len = n;
    }
    lean_dec(pair);
    return envelope;
}

/* Release a buffer returned by l4_version_c / l4_bgp_query_c /
   l4_call_c / l4_call_blob_c, or the ENVELOPE of l4_call_blob_io_c. */
L4_EXPORT void l4_free_result(char *p) { free(p); }

/* Release the byte region l4_call_blob_io_c wrote through `out_ptr`.
   Kept apart from l4_free_result on purpose -- see the ownership note
   on l4_call_blob_io_c. */
L4_EXPORT void l4_free_blob(uint8_t *p) { free(p); }
