/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-compilation -skip-makefiles -tmpdir krml-output/groupC-c -warn-error +2+9 -bundle RDF.Store.Columnar.DeltaLog=*[rename=Factoidal_DeltaLog] krml-output/groupC/out.krml
  F* version: <unknown>
  KaRaMeL version: 11bb8e1ac2f720fb7144b9b768c7251526caa149
 */

#ifndef krmlinit_H
#define krmlinit_H

#include "krmllib.h"

#if defined(__GNUC__) && !(defined(_WIN32) || defined(_WIN64))
__attribute__ ((visibility ("hidden")))
#endif

void krmlinit_globals(void);


#define krmlinit_H_DEFINED
#endif /* krmlinit_H */
