/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-compilation -skip-makefiles -tmpdir krml-output/groupC-c -warn-error +2+9 -bundle RDF.Store.Columnar.DeltaLog=*[rename=Factoidal_DeltaLog] krml-output/groupC/out.krml
  F* version: <unknown>
  KaRaMeL version: 11bb8e1ac2f720fb7144b9b768c7251526caa149
 */

#include "krmlinit.h"

#include "Factoidal_DeltaLog.h"
#include "internal/Factoidal_DeltaLog.h"

#if defined(__GNUC__) && !(defined(_WIN32) || defined(_WIN64))
__attribute__ ((visibility ("hidden")))
#endif

void krmlinit_globals(void)
{
  RDF_Store_Columnar_DeltaLog_serialize_log_header =
    FStar_List_Tot_Base_append__FStar_Char_char(RDF_Bytes_write_u32_le(RDF_Store_Columnar_DeltaLog_delta_log_magic),
      RDF_Bytes_write_u32_le(RDF_Store_Columnar_DeltaLog_delta_log_version));
}

