/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-compilation -skip-makefiles -tmpdir krml-output/groupC-c -warn-error +2+9 -bundle RDF.Store.Columnar.DeltaLog=*[rename=Factoidal_DeltaLog] krml-output/groupC/out.krml
  F* version: <unknown>
  KaRaMeL version: 11bb8e1ac2f720fb7144b9b768c7251526caa149
 */

#ifndef internal_Factoidal_DeltaLog_H
#define internal_Factoidal_DeltaLog_H

#include "krmllib.h"

#include "../Factoidal_DeltaLog.h"

Prims_list__FStar_Char_char *RDF_Bytes_write_u32_le(krml_checked_int_t n);

typedef struct K___Prims_list__FStar_Char_char_Prims_list__FStar_Char_char_s
{
  Prims_list__FStar_Char_char *fst;
  Prims_list__FStar_Char_char *snd;
}
K___Prims_list__FStar_Char_char_Prims_list__FStar_Char_char;

typedef struct
FStar_Pervasives_Native_option___Prims_list__FStar_Char_char___Prims_list__FStar_Char_char__s
{
  FStar_Pervasives_Native_option___krml_checked_int_t___Prims_list__FStar_Char_char__tags tag;
  K___Prims_list__FStar_Char_char_Prims_list__FStar_Char_char v;
}
FStar_Pervasives_Native_option___Prims_list__FStar_Char_char___Prims_list__FStar_Char_char_;

FStar_Pervasives_Native_option___Prims_list__FStar_Char_char___Prims_list__FStar_Char_char_
RDF_Bytes_parse_n_bytes(krml_checked_int_t n, Prims_list__FStar_Char_char *bs);

bool
RDF_Term_string_has_colon_from(Prims_string s, krml_checked_int_t pos, krml_checked_int_t fuel);

Prims_list__FStar_Char_char
*FStar_List_Tot_Base_append__FStar_Char_char(
  Prims_list__FStar_Char_char *x,
  Prims_list__FStar_Char_char *y
);

krml_checked_int_t
FStar_List_Tot_Base_length__FStar_Char_char(Prims_list__FStar_Char_char *uu___);

krml_checked_int_t
FStar_List_Tot_Base_length__RDF_Store_Columnar_DeltaLog_delta_entry(
  Prims_list__RDF_Store_Columnar_DeltaLog_delta_entry *uu___
);


#define internal_Factoidal_DeltaLog_H_DEFINED
#endif /* internal_Factoidal_DeltaLog_H */
