/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-compilation -skip-makefiles -tmpdir c-output -warn-error +2 -bundle RDF.Format+SPARQL.JSON.Escape+SPARQL.HTTP.StaticFiles+SPARQL.HTTP.QueriesIndex=*[rename=Factoidal_Pilot] krml-output/groupA/out.krml
  F* version: <unknown>
  KaRaMeL version: 11bb8e1ac2f720fb7144b9b768c7251526caa149
 */

#ifndef internal_Factoidal_Pilot_H
#define internal_Factoidal_Pilot_H

#include "krmllib.h"

#include "../Factoidal_Pilot.h"

Prims_list__SPARQL_HTTP_QueriesIndex_query_entry
*FStar_List_Tot_Base_append__SPARQL_HTTP_QueriesIndex_query_entry(
  Prims_list__SPARQL_HTTP_QueriesIndex_query_entry *x,
  Prims_list__SPARQL_HTTP_QueriesIndex_query_entry *y
);


#define internal_Factoidal_Pilot_H_DEFINED
#endif /* internal_Factoidal_Pilot_H */
