/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-compilation -warn-error -9-11-15 -add-include "krml/internal/compat.h" -tmpdir /tmp/rdf-c-output RDF.Graph.Executable.fst
  F* version: <unknown>
  KaRaMeL version: d7a8f9ec
 */

#ifndef internal_FStar_H
#define internal_FStar_H

#include "krmllib.h"

#include "../FStar.h"
#include "krml/internal/compat.h"

krml_checked_int_t FStar_Char_int_of_char(FStar_Char_char c);

extern Prims_list__FStar_Char_char *FStar_String_list_of_string(Prims_string uu___);

extern krml_checked_int_t FStar_String_strlen(Prims_string s);

extern Prims_string FStar_String_concat(Prims_string uu___, Prims_list__Prims_string *uu___1);

extern krml_checked_int_t FStar_String_compare(Prims_string uu___, Prims_string uu___1);

extern Prims_string FStar_String_lowercase(Prims_string uu___);

extern Prims_string FStar_String_uppercase(Prims_string uu___);

extern Prims_string
FStar_String_sub(Prims_string s, krml_checked_int_t i, krml_checked_int_t l);


#define internal_FStar_H_DEFINED
#endif /* internal_FStar_H */
