/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-compilation -warn-error -9-11-15 -add-include "krml/internal/compat.h" -tmpdir /tmp/rdf-c-output RDF.Graph.Executable.fst
  F* version: <unknown>
  KaRaMeL version: d7a8f9ec
 */

#ifndef internal_RDF_Graph_Executable_H
#define internal_RDF_Graph_Executable_H

#include "krmllib.h"

#include "FStar.h"
#include "../RDF_Graph_Executable.h"
#include "krml/internal/compat.h"

Prims_list__Prims_string
*FStar_List_Tot_Base_append__Prims_string(
  Prims_list__Prims_string *x,
  Prims_list__Prims_string *y
);

RDF_Graph_Executable_rdf_graph_gc
*FStar_List_Tot_Base_append__RDF_Graph_Executable_triple(
  RDF_Graph_Executable_rdf_graph_gc *x,
  RDF_Graph_Executable_rdf_graph_gc *y
);

RDF_Graph_Executable_rdf_graph_gc
*FStar_List_Tot_Base_filter__RDF_Graph_Executable_triple(
  bool (*f)(RDF_Graph_Executable_triple x0),
  RDF_Graph_Executable_rdf_graph_gc *uu___
);

krml_checked_int_t
FStar_List_Tot_Base_length__RDF_Graph_Executable_triple(
  RDF_Graph_Executable_rdf_graph_gc *uu___
);

FStar_Pervasives_Native_option__RDF_Graph_Executable_rdf_term
FStar_List_Tot_Base_assoc__Prims_string_RDF_Graph_Executable_rdf_term(
  Prims_string x,
  Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *uu___
);


#define internal_RDF_Graph_Executable_H_DEFINED
#endif /* internal_RDF_Graph_Executable_H */
