-- L4Factoidal — Lean 4 port of the Factoidal F* RDF/SPARQL core.
-- See PORT_NOTES.md for scope, correspondences, and the assumption
-- report against the F* originals.
import L4Factoidal.Crypto.SHA2
import L4Factoidal.Crypto.SHA2Theorems
import L4Factoidal.Crypto.SHA2Tests
import L4Factoidal.Crypto.MD5
import L4Factoidal.Crypto.SHA1
import L4Factoidal.RDF.ListHelpers
import L4Factoidal.RDF.XmlCanon
import L4Factoidal.RDF.Core
import L4Factoidal.RDF.Graph
import L4Factoidal.RDF.StoreLoader
import L4Factoidal.RDF.StoreCapabilities
import L4Factoidal.RDF.StoreCapabilitiesCottas
import L4Factoidal.RDF.StoreDeltaMerge
import L4Factoidal.RDF.StoreCapabilitiesDelta
import L4Factoidal.RDF.StoreCombine
import L4Factoidal.RDF.Isomorphism
import L4Factoidal.RDF.IsomorphismTheorems
import L4Factoidal.RDF.IsomorphismTests
import L4Factoidal.SPARQL.PropertyPath
import L4Factoidal.SPARQL.Algebra
import L4Factoidal.SPARQL.AlgebraSpec
import L4Factoidal.SPARQL.AlgebraRefinement
import L4Factoidal.SPARQL.JoinRefinement
import L4Factoidal.SPARQL.IndexedEvalRefinement
import L4Factoidal.SPARQL.StoreBackend
import L4Factoidal.SPARQL.StorePlan
import L4Factoidal.SPARQL.StoreFastPath
import L4Factoidal.SPARQL.StoreDataset
import L4Factoidal.SPARQL.AskBgpRoundTrip
import L4Factoidal.SPARQL.AskBgpRoundTripString
import L4Factoidal.SPARQL.RewriteVarStrip
import L4Factoidal.SPARQL.Invariants
import L4Factoidal.RDFS.Vocabulary
import L4Factoidal.RDFS.RdfsCore
import L4Factoidal.RDFS.Closure
import L4Factoidal.RDFS.ClosureTheorems
import L4Factoidal.RDFS.ClosureTests
import L4Factoidal.RDFS.FixedPoint
import L4Factoidal.RDFS.RhoDfCompleteness
import L4Factoidal.RDFS.ReflexivityWitness
import L4Factoidal.RDFS.FullClosure
import L4Factoidal.RDFS.FullClosureTheorems
import L4Factoidal.RDFS.Derivation
import L4Factoidal.RDFS.DerivationTests
import L4Factoidal.RDFS.DerivationCheck
import L4Factoidal.RDFS.DerivationCheckTests
import L4Factoidal.Proof.Syntax
import L4Factoidal.Proof.Checker
import L4Factoidal.Proof.Tests
import L4Factoidal.RDFS.SchemaSplit
import L4Factoidal.RDF.Datatypes
import L4Factoidal.RDF.Entailment
import L4Factoidal.RDF.EntailmentTheorems
import L4Factoidal.RDF.EntailmentSimpleRefinement
import L4Factoidal.RDF.EntailmentTests
import L4Factoidal.RDF.EntailmentSimpleSpec
import L4Factoidal.RDF.EntailmentRdfSpec
import L4Factoidal.RDF.EntailmentRdfsSpec
import L4Factoidal.RDF.Semantics
import L4Factoidal.SPARQL.Expr
import L4Factoidal.SPARQL.ExprTheorems
import L4Factoidal.SPARQL.ExprRefinement
import L4Factoidal.SPARQL.Query
import L4Factoidal.SPARQL.Exists
import L4Factoidal.SPARQL.QueryTheorems
import L4Factoidal.SPARQL.QueryTests
import L4Factoidal.Syntax.Lexing
import L4Factoidal.Syntax.Locality
import L4Factoidal.Syntax.LocalityLiteral
import L4Factoidal.Syntax.LocalityLine
import L4Factoidal.Syntax.LocalitySuffix
import L4Factoidal.Syntax.LocalitySkips
import L4Factoidal.Syntax.LocalityCount
import L4Factoidal.Syntax.IriScan
import L4Factoidal.Syntax.NTriples
import L4Factoidal.Syntax.NTriplesRoundTrip
import L4Factoidal.Syntax.NQuads
import L4Factoidal.Syntax.NQuadsStreaming
import L4Factoidal.Syntax.NQuadsConcat
import L4Factoidal.Syntax.NQuadsHomomorphism
import L4Factoidal.Syntax.NQuadsFold
import L4Factoidal.Syntax.LexShift
import L4Factoidal.Syntax.IriResolve
import L4Factoidal.Syntax.Turtle
import L4Factoidal.Syntax.TurtleSerialize
import L4Factoidal.Syntax.TriG
import L4Factoidal.Syntax.TurtleTests
import L4Factoidal.Syntax.TurtleTheorems
import L4Factoidal.Syntax.SyntaxTests
import L4Factoidal.Syntax.SyntaxTheorems
import L4Factoidal.Syntax.RdfXml
import L4Factoidal.Syntax.RdfXmlTests
import L4Factoidal.Syntax.RdfXmlTheorems
import L4Factoidal.JSON.Value
import L4Factoidal.JSON.Parser
import L4Factoidal.JSON.Serialize
import L4Factoidal.JSON.Tests
import L4Factoidal.JSON.Theorems
import L4Factoidal.RDF.Canonical
import L4Factoidal.RDF.CanonicalTheorems
import L4Factoidal.RDF.CanonicalTests
import L4Factoidal.Tests
import L4Factoidal.SPARQL.ExprTests
import L4Factoidal.XML.Document
import L4Factoidal.XML.Parser
import L4Factoidal.XML.Namespaces
import L4Factoidal.XML.Wellformedness
import L4Factoidal.XML.Theorems
import L4Factoidal.XML.Tests
import L4Factoidal.OWL.Vocabulary
import L4Factoidal.OWL.QueryRewriteCore
import L4Factoidal.OWL.QueryRewriteFlat
import L4Factoidal.OWL.QueryRewritePattern
import L4Factoidal.OWL.QueryRewriteRestriction
import L4Factoidal.OWL.QueryRewriteExpand
import L4Factoidal.OWL.QueryRewriteJoins
import L4Factoidal.OWL.QueryRewriteNested
import L4Factoidal.OWL.QueryMaterialise
import L4Factoidal.OWL.QueryEval
import L4Factoidal.OWL.QueryEvalRegimeTests
import L4Factoidal.OWL.RLRules
import L4Factoidal.OWL.RLClosure
import L4Factoidal.OWL.RLClosureIndexed
import L4Factoidal.OWL.RLSemantics
import L4Factoidal.OWL.RLHerbrand
import L4Factoidal.OWL.RLTheorems
import L4Factoidal.OWL.RLTests
import L4Factoidal.OWL.Semantics
import L4Factoidal.RDF.EntailmentRdfsModelTheory
import L4Factoidal.RDF.SemanticsHypothesisWitness
import L4Factoidal.RDF.EntailmentSimpleBoundary
import L4Factoidal.RDF.EntailmentRdfsDatatypeClash
import L4Factoidal.OWL.Tableau
import L4Factoidal.OWL.TableauTheorems
import L4Factoidal.OWL.TableauTests
import L4Factoidal.SPARQL.Results
import L4Factoidal.SPARQL.ResultsXml
import L4Factoidal.SPARQL.ResultsJson
import L4Factoidal.SPARQL.ResultsCsvTsv
import L4Factoidal.SPARQL.ResultsTests
import L4Factoidal.SPARQL.ResultsTheorems
import L4Factoidal.JSONLD.Loader
import L4Factoidal.JSONLD.Context
import L4Factoidal.JSONLD.Expand
import L4Factoidal.JSONLD.ToRdf
import L4Factoidal.JSONLD.FromRdf
import L4Factoidal.JSONLD.Compact
import L4Factoidal.JSONLD.Flatten
import L4Factoidal.JSONLD.Html
import L4Factoidal.JSONLD.ApiTests
import L4Factoidal.JSONLD.Tests
import L4Factoidal.JSONLD.Theorems
import L4Factoidal.JSONLD.Frame
import L4Factoidal.SPARQL.Tokenizer
import L4Factoidal.SPARQL.TokenizerLemmas
import L4Factoidal.SPARQL.TokenizeChain
import L4Factoidal.SPARQL.AskRoundTrip
import L4Factoidal.SPARQL.SkipWsLemmas
import L4Factoidal.SPARQL.TokenRoundTrip
import L4Factoidal.SPARQL.Parser
import L4Factoidal.SPARQL.ParserTests
import L4Factoidal.SPARQL.ParserTheorems
import L4Factoidal.SPARQL.Update
import L4Factoidal.SPARQL.UpdateParser
import L4Factoidal.SPARQL.UpdateTests
import L4Factoidal.SPARQL.UpdateTheorems
import L4Factoidal.Regex.Syntax
import L4Factoidal.Regex.Derivative
import L4Factoidal.Regex.Exec
import L4Factoidal.Regex.XSDPattern
import L4Factoidal.Regex.XPath
import L4Factoidal.Regex.RegexTests
import L4Factoidal.Regex.RegexTheorems
import L4Factoidal.SPARQL.Protocol
import L4Factoidal.SPARQL.GraphStore
import L4Factoidal.SPARQL.ServiceDescription
import L4Factoidal.SPARQL.ProtocolTests
import L4Factoidal.SPARQL.ProtocolTheorems
import L4Factoidal.SPARQL.ProtocolClient
import L4Factoidal.SHACL.Vocabulary
import L4Factoidal.SHACL.Shapes
import L4Factoidal.SHACL.Validation
import L4Factoidal.SHACL.Report
import L4Factoidal.SHACL.Sparql
import L4Factoidal.SHACL.ShaclTests
import L4Factoidal.SHACL.ShaclTheorems
import L4Factoidal.SHACL.SparqlTheorems
import L4Factoidal.SHACL.Rules
import L4Factoidal.SHACL.NodeExpr
import L4Factoidal.Testing.Gen
import L4Factoidal.Testing.Props
import L4Factoidal.Testing.GenTests
import L4Factoidal.Crypto.Ed25519
import L4Factoidal.VC.Multibase
import L4Factoidal.VC.DidKey
import L4Factoidal.VC.Context
import L4Factoidal.VC.DataIntegrity
import L4Factoidal.VC.Tests
import L4Factoidal.VC.Theorems
import L4Factoidal.Geo.Types
import L4Factoidal.Geo.Order
import L4Factoidal.Geo.BBox
import L4Factoidal.Geo.Topology
import L4Factoidal.Geo.Wkt
import L4Factoidal.Geo.WktTests
import L4Factoidal.Geo.Functions
import L4Factoidal.Geo.FunctionsTests
import L4Factoidal.Geo.Tests
import L4Factoidal.CSVW.Dialect
import L4Factoidal.CSVW.DialectTests
import L4Factoidal.CSVW.UriTemplate
import L4Factoidal.CSVW.UriTemplateTests
import L4Factoidal.CSVW.Metadata
import L4Factoidal.CSVW.MetadataTests
import L4Factoidal.CSVW.Conversion
import L4Factoidal.CSVW.ConversionTests
import L4Factoidal.CSVW.Emit
import L4Factoidal.CSVW.EmitTests
import L4Factoidal.CSVW.Formats
import L4Factoidal.CSVW.FormatsTests
import L4Factoidal.CSVW.Json
import L4Factoidal.CSVW.JsonTests
import L4Factoidal.CSVW.Validate
import L4Factoidal.CSVW.ValidateTests
import L4Factoidal.CSVW.Pipeline
import L4Factoidal.CSVW.PipelineTests
import L4Factoidal.ShEx.Schema
import L4Factoidal.ShEx.Validation
import L4Factoidal.ShEx.Tests
import L4Factoidal.ShEx.Shapes
import L4Factoidal.ShEx.ShapesTests
import L4Factoidal.ShEx.FromJson
import L4Factoidal.ShEx.SchemaEq
import L4Factoidal.ShEx.Compact
import L4Factoidal.ShEx.CompactTests
import L4Factoidal.RML.Mapping
import L4Factoidal.RML.Tests
import L4Factoidal.RML.JsonPath
import L4Factoidal.RML.Sources
import L4Factoidal.RML.Value
import L4Factoidal.RML.Model
import L4Factoidal.RML.FromGraph
import L4Factoidal.RML.Eval
import L4Factoidal.RML.EvalTests
import L4Factoidal.RML.VirtualSource
import L4Factoidal.RIF.Syntax
import L4Factoidal.RIF.Ps
import L4Factoidal.RIF.Builtins
import L4Factoidal.RIF.Engine
import L4Factoidal.RIF.EngineTests
import L4Factoidal.RIF.EngineTheorems
import L4Factoidal.RIF.Translation
import L4Factoidal.RIF.Conformance
import L4Factoidal.RIF.Xml
import L4Factoidal.JSONSchema.Validate
import L4Factoidal.JSONSchema.Tests
import L4Factoidal.XPath.Number
import L4Factoidal.XPath.NumberTests
import L4Factoidal.Schematron.Validate
import L4Factoidal.Schematron.Tests
import L4Factoidal.Schematron.FromXml
import L4Factoidal.Schematron.FromXmlTests
import L4Factoidal.XPath.Mini
import L4Factoidal.XPath.MiniTests
import L4Factoidal.XPath.Data
import L4Factoidal.XPath.Expr
import L4Factoidal.XPath.Eval
import L4Factoidal.XPath.ExprTests
import L4Factoidal.HTTP.Server
import L4Factoidal.HTTP.Tests
import L4Factoidal.Storage.Bytes
import L4Factoidal.Storage.Tests
import L4Factoidal.MathML.Core
import L4Factoidal.MathML.Tests
import L4Factoidal.XSLT.Templates
import L4Factoidal.XSLT.Tests
import L4Factoidal.XSLT.Transform
import L4Factoidal.XSLT.TransformTests
import L4Factoidal.OWL.ClassExpr
import L4Factoidal.OWL.CountingOracle
import L4Factoidal.OWL.FunctionalSyntax
import L4Factoidal.OWL.SyntaxDL
import L4Factoidal.OWL.FunctionalSyntaxTests
import L4Factoidal.OWL.ClassExprTests
import L4Factoidal.OWL.Materialise
import L4Factoidal.OWL.MaterialiseTests
import L4Factoidal.Testing.Enumerate
import L4Factoidal.XSD.Facets
import L4Factoidal.XSD.FacetsTests
import L4Factoidal.OWL.Refute
import L4Factoidal.OWL.NegationGoals
import L4Factoidal.OWL.RefuteTests
import L4Factoidal.HTTP.Client
import L4Factoidal.HTTP.ClientTests
import L4Factoidal.HTTP.RunQuery
import L4Factoidal.HTTP.RunQueryTests
import L4Factoidal.HTTP.Ops
import L4Factoidal.HTTP.OpsTests
import L4Factoidal.Math.Subst
import L4Factoidal.Math.Simplify
import L4Factoidal.Math.Diff
import L4Factoidal.Math.Series
import L4Factoidal.Math.Matrix
import L4Factoidal.Math.Tests
import L4Factoidal.Math.Sigmoid
import L4Factoidal.Math.SigmoidTests
import L4Factoidal.XForms.Bind
import L4Factoidal.HTTP.Client
import L4Factoidal.HTTP.ClientTests
import L4Factoidal.HTTP.RunQuery
import L4Factoidal.HTTP.RunQueryTests
import L4Factoidal.HTTP.Ops
import L4Factoidal.HTTP.OpsTests
import L4Factoidal.Math.Subst
import L4Factoidal.Math.Simplify
import L4Factoidal.Math.Diff
import L4Factoidal.Math.Series
import L4Factoidal.Math.Matrix
import L4Factoidal.Math.Tests
import L4Factoidal.Math.Sigmoid
import L4Factoidal.Math.SigmoidTests
import L4Factoidal.XForms.BindTests
import L4Factoidal.GRDDL.Discovery
import L4Factoidal.Storage.DeltaLog
import L4Factoidal.Storage.DeltaLogTests
import L4Factoidal.Storage.BlockMvp
import L4Factoidal.Storage.BlockMvpTests
import L4Factoidal.Storage.BlockWireV0
import L4Factoidal.Storage.BlockWireV0Tests
import L4Factoidal.VC.Credential
import L4Factoidal.VC.CredentialTests
import L4Factoidal.HDT.Container
import L4Factoidal.HDT.ContainerTheorems
import L4Factoidal.HDT.Dictionary
import L4Factoidal.HDT.Triples
import L4Factoidal.HDT.Store
import L4Factoidal.XSD.IEEE754
import L4Factoidal.XSD.IEEE754Tests
import L4Factoidal.Dep.Reachability
import L4Factoidal.RDFS.SemiNaive
import L4Factoidal.RDF.DatasetGraphs
import L4Factoidal.SPARQL.UpdateAnalysis
import L4Factoidal.SPARQL.QueryAnalysis
import L4Factoidal.SPARQL.PlanStreamable
import L4Factoidal.RDF.CanonicalManifest
import L4Factoidal.RDF.DatasetMerge
import L4Factoidal.RDF.Format
import L4Factoidal.SPARQL.JsonEscape
import L4Factoidal.SPARQL.EvalLimits
import L4Factoidal.SPARQL.TimeBudget
import L4Factoidal.OWL.DirectMappingFilter
import L4Factoidal.RDFS.RDFSPlus
import L4Factoidal.RDF.Pretty
import L4Factoidal.SPARQL.Explain
import L4Factoidal.SPARQL.Diagnostics
import L4Factoidal.SPARQL.BgpRefinement
import L4Factoidal.SPARQL.EntailmentRegimeRdfs
import L4Factoidal.SPARQL.FullText
import L4Factoidal.SPARQL.UpdateSandbox
import L4Factoidal.OWL.TestsManifest
import L4Factoidal.RDFS.RegimeDispatch
import L4Factoidal.RDF.VocabularyAxioms
import L4Factoidal.Cottas.SortByKey
import L4Factoidal.Cottas.PresenceBitmap
import L4Factoidal.Cottas.OnDiskIndex
import L4Factoidal.Cottas.PageCache
import L4Factoidal.Cottas.DictWriter
import L4Factoidal.Cottas.BaseWriterPrims
import L4Factoidal.Cottas.BaseWriterThrift
import L4Factoidal.Cottas.BaseWriterColumn
import L4Factoidal.Cottas.BaseWriterDict
import L4Factoidal.Cottas.BaseWriterFile
import L4Factoidal.Cottas.BaseWriterFileV2
import L4Factoidal.Cottas.OnDiskStore
import L4Factoidal.Cottas.OnDiskFilter
import L4Factoidal.Cottas.OnDiskWalk
import L4Factoidal.Cottas.OnDiskLimit
import L4Factoidal.Cottas.OnDiskPlan
import L4Factoidal.Cottas.OnDiskSearch
import L4Factoidal.Cottas.OnDiskCount
import L4Factoidal.Cottas.OnDiskSelective
import L4Factoidal.Cottas.OnDiskCountExact
import L4Factoidal.Cottas.CompoundPresenceBitmap
import L4Factoidal.Cottas.PlanPruning
import L4Factoidal.Cottas.AccessPath
import L4Factoidal.Cottas.Ballyhoo
import L4Factoidal.Cottas.PresenceWriter
import L4Factoidal.Cottas.CompoundPresenceWriter
import L4Factoidal.Cottas.OffsetsWriter
import L4Factoidal.Cottas.SubjectOffsetsWriter
import L4Factoidal.Cottas.LazyDict
import L4Factoidal.Cottas.LazyDictRegistry
import L4Factoidal.Cottas.LazyTermCache
import L4Factoidal.Cottas.OffsetIndex
import L4Factoidal.Cottas.SubjectOffsetIndex
import L4Factoidal.Storage.IndexedBlock
import L4Factoidal.Storage.IndexedBlockTests
import L4Factoidal.Storage.BlockArtifact
import L4Factoidal.Storage.BlockArtifactTests
import L4Factoidal.Storage.IndexedBlockWireV1
import L4Factoidal.Storage.IndexedBlockWireV1Tests
import L4Factoidal.Storage.IndexedBlockWireV2
import L4Factoidal.Storage.IndexedBlockWireV2Tests
import L4Factoidal.CL.Syntax
import L4Factoidal.CL.Clif
import L4Factoidal.CL.Alpha
import L4Factoidal.CL.Semantics
import L4Factoidal.CL.Examples
import L4Factoidal.CL.FiniteSat
import L4Factoidal.CL.FiniteSatTheorems
import L4Factoidal.CL.ClifAdequacy
import L4Factoidal.CL.Normalize
import L4Factoidal.CL.IklModels
import L4Factoidal.CL.NormalizeSemantics
import L4Factoidal.Unified.Theory
import L4Factoidal.Unified.RdfEmbed
import L4Factoidal.Unified.RdfTransport
import L4Factoidal.Unified.RdfAdequacy
import L4Factoidal.Unified.DatasetEmbed
import L4Factoidal.Unified.DSchema
import L4Factoidal.Unified.RhoDfSchema
import L4Factoidal.Unified.RdfsSchema
import L4Factoidal.Unified.Datalog
import L4Factoidal.Unified.DatalogClosures
import L4Factoidal.Unified.OwlRlSchema
import L4Factoidal.Unified.OwlRlAdequacy
import L4Factoidal.Unified.OwlDlDirect
import L4Factoidal.Unified.OwlDlAdequacy
import L4Factoidal.Unified.SparqlQuery
import L4Factoidal.Unified.SparqlAdequacy
import L4Factoidal.Unified.SparqlAlgebra
import L4Factoidal.Unified.Witnesses
import L4Factoidal.Unified.ClBridge
import L4Factoidal.Unified.RifEmbed
