/-
L4Factoidal.RML.VirtualSource — RML as a queryable store, not a
materialised graph.

Port of `formal/fstar/RML.VirtualSource.fst` (375 lines).

A `StoreCaps` over an already-decoded RML mapping and its already-read
source documents. It answers a bound triple pattern WITHOUT running the
mapping's full materialising evaluation for every query.

## The pushdown model

1. **Structural narrowing.** A triples map is ruled out without reading
   a single record when its SUBJECT map is a constant that is not the
   bound subject, or when every predicate it can produce — the
   predicate-object maps' predicates plus the `rml:class` shortcut for
   `rdf:type` — is a constant that is not the bound predicate. A
   reference or template map always stays a candidate, because
   evaluating it is the only way to know.

2. **Record-level subject pushdown.** Inside a surviving candidate,
   when the subject is bound and the subject map is not a plain
   constant, each record's SUBJECT ALONE is evaluated and the record is
   dropped before the full per-record machinery runs on it.

3. **A bound OBJECT is not pushed down.** Every surviving candidate's
   records reach full evaluation whatever the object bound; the final
   exact-match filter still gives the right answer.

4. **Joins do not push down.** `rml:parentTriplesMap` object maps are
   evaluated the way they always are, per candidate map. A query that
   needs join-shaped data joins two triple patterns over this same store
   at the SPARQL level.

## The record index is preserved through the filter, and the F\* source
does not do this

`quadsOfRecords` takes records already paired with their index, and the
pushdown filters that paired list, so a surviving record keeps the index
it had in the source. This matters because `anonLabel` turns the index
into a blank-node label.

The F\* module filters the record list and then re-indexes it, so the
blank node generated by source record `k` is labelled from `k` under an
unbound pattern and from its position among the SURVIVING records under
a bound one. Every blank node the record generates moves. Filed as
<https://github.com/danbri/factoidal/issues/558>, with the join case
that returns no rows because of it. This port does not reproduce that
behaviour, and a `#guard` below pins the difference.

## Scope

Default graph only, as in the F\* source: a triple routed to a named
graph by a graph map is DROPPED rather than misrouted, and
`supportsNamedGraphs` is `false` so the flag says so.
-/
import L4Factoidal.RML.Eval
import L4Factoidal.RDF.StoreCapabilities

namespace L4Factoidal.RML

open L4Factoidal.RDF
open L4Factoidal.SPARQL (PatternBound patternBoundAll tripleMatchesBound)
open L4Factoidal.JSON

/-! ## The store's inputs

One already-parsed document per source path, and the mapping. Both are
read once when the store is built; every query walks them again as pure
values. -/

structure VirtualSource where
  mapping : Mapping
  /-- Source path to its already-parsed document. A path with no entry
  yields no records, which is how an unread file behaves. -/
  docs : List (String × Json)
  /-- The base IRI in force where a triples map states none. -/
  baseIri : Option String := none

def VirtualSource.docFor (vs : VirtualSource) (path : String) : Option Json :=
  (vs.docs.find? (fun p => p.1 == path)).map Prod.snd

/-! ## Structural narrowing -/

/-- A bound predicate rules out a constant predicate map that is not
that IRI. Anything else stays a candidate. -/
def singlePmCouldMatch (p : WfIri) (pm : TermMap) : Bool :=
  match pm.form with
  | .constant (.iri i) => i == p
  | .constant _        => false
  | _                  => true

def pomPredicateCouldMatch (p : WfIri) (pom : PredicateObjectMap) : Bool :=
  pom.predicates.any (singlePmCouldMatch p)

/-- `rml:class` is a constant-predicate shortcut: a non-empty class list
contributes `rdf:type` triples and nothing else. -/
def classesCouldMatchPredicate (p : WfIri) (classes : List String) : Bool :=
  match classes with
  | [] => false
  | _  => p == rdfTypeIri

def bpCouldMatch (bp : Option WfIri) (classes : List String)
    (poms : List PredicateObjectMap) : Bool :=
  match bp with
  | none => true
  | some p => classesCouldMatchPredicate p classes || poms.any (pomPredicateCouldMatch p)

/-- A bound subject rules out a constant subject map whose term is not
that subject. A reference or template subject map stays a candidate;
record-level pushdown is where those are narrowed. -/
def smCouldMatchSubject (bs : Option Subject) (sm : TermMap) : Bool :=
  match bs with
  | none => true
  | some s =>
      match sm.form with
      | .constant t =>
          match t with
          | .iri i   => Subject.eqb s (.iri i)
          | .bnode b => Subject.eqb s (.bnode b)
          | _        => false
      | _ => true

def triplesMapCouldMatch (b : PatternBound) (tm : TriplesMap) : Bool :=
  smCouldMatchSubject b.s tm.subject && bpCouldMatch b.p tm.classes tm.poms

/-! ## Record-level subject pushdown

The cheapest per-record probe is the subject alone, through the same
`subjectsOf` the full evaluation uses. The record keeps its index, so
the probe sees the SAME blank-node label the full evaluation will
produce — which is what makes the pushdown invisible in the result. -/

def recordMatchesBoundSubject (bs : Option Subject) (tm : TriplesMap)
    (rec' : Json) (i : Nat) : Bool :=
  match bs with
  | none => true
  | some s =>
      match tm.subject.form with
      | .constant _ => true      -- structural narrowing already settled this
      | _ => (subjectsOf tm rec' i).any (fun s' => Subject.eqb s s')

/-- The indexed records of one candidate map that survive the pushdown. -/
def recordsForMap (vs : VirtualSource) (b : PatternBound) (tm : TriplesMap) :
    List (Json × Nat) :=
  match vs.docFor tm.source.path with
  | none => []
  | some doc =>
      ((recordsOf tm.source doc).zipIdx).filter
        (fun (rec', i) => recordMatchesBoundSubject b.s tm rec' i)

/-! ## Solving

Default graph only: a quad with a graph is dropped, not misrouted. -/

def solveOneMap (vs : VirtualSource) (b : PatternBound) (tm : TriplesMap) : Graph :=
  let tms := vs.mapping.map (fun t => { t with base := t.base.orElse (fun _ => vs.baseIri) })
  let tm := { tm with base := tm.base.orElse (fun _ => vs.baseIri) }
  (quadsOfRecords tms vs.docFor tm (recordsForMap vs b tm)).filterMap (fun q =>
    match q.g with
    | none => some ({ s := q.s, p := q.p, o := q.o } : Triple)
    | some (.iri i) => if i.val == defaultGraphIri
                       then some ({ s := q.s, p := q.p, o := q.o } : Triple)
                       else none
    | some _ => none)

/-- A graph is a SET of triples. A source with duplicate records
generates the same triple more than once, but the materialised graph
carries it once, so the virtual answer must too. First occurrence wins,
and the comparison is the engine equality `Graph.mem` uses. -/
def dedupeTriples (ts : Graph) : Graph :=
  ts.foldl (fun acc t => if Graph.mem t acc then acc else acc ++ [t]) []

def rmlSolve (vs : VirtualSource) (b : PatternBound) : Graph :=
  let candidates := vs.mapping.filter (triplesMapCouldMatch b)
  dedupeTriples (tripleMatchesBound b (candidates.flatMap (solveOneMap vs b)))

/-! ## Pushdown evidence

How many records of each surviving candidate would reach full
evaluation. Every function involved is pure, so this is a number a test
can compare directly rather than something that needs instrumentation. -/

def recordsConsideredForMap (vs : VirtualSource) (b : PatternBound) (tm : TriplesMap) : Nat :=
  (recordsForMap vs b tm).length

def rmlSolveTrace (vs : VirtualSource) (b : PatternBound) : List (String × Nat) :=
  (vs.mapping.filter (triplesMapCouldMatch b)).map
    (fun tm => (tm.id, recordsConsideredForMap vs b tm))

/-! ## The capability record

`estimate` and `countExact` are both full solves, so `estimateIsExact`
is `true`. That says exact, not cheap: it costs one walk of the records
either way. -/

def capsOfRmlSource (vs : VirtualSource) : StoreCaps :=
  { flags :=
      { supportsNamedGraphs := false   -- default graph only
      , supportsUpdate := false        -- read-only, no write seam
      , streamingShapes := true
      , estimateIsExact := true        -- exact, not cheap
      , canReportDecodeFail := false }
  , solve := fun b => rmlSolve vs b
  , solveLimited := fun b n => capsTakeN n (rmlSolve vs b)
  , estimate := fun b => (rmlSolve vs b).length
  , countExact := fun b => (rmlSolve vs b).length
  , predicatePresent := fun pred => (rmlSolve vs { p := some pred }).length > 0
  , decodeFailure := fun _ => false
    -- a virtual source has no dictionary pages to enumerate
  , distinctPredicates := none
    -- nothing is decoded lazily, so there is nothing to defer
  , solveSelective := none }

/-! ## Build-time checks -/

section Checks

private def iriW (s : String) : WfIri :=
  if h : isIri s then ⟨s, h⟩ else ⟨"http://e.org/", by decide⟩

/-- Three records, two of them for Alice. -/
private def doc : Json :=
  .array [ .object [("id", .string "1"), ("name", .string "Alice")]
       , .object [("id", .string "2"), ("name", .string "Bob")]
       , .object [("id", .string "3"), ("name", .string "Alice")] ]

private def nameTm : TriplesMap :=
  { id := "http://e.org/tm/name"
  , source := { path := "people.json", iterator := some "$[*]",
                refFormulation := "http://w3id.org/rml/JSONPath" }
  , subject := { form := .template "http://e.org/p/{$.id}" }
  , poms := [ { predicates := [{ form := .constant (.iri (iriW "http://e.org/name")) }]
              , objects := [.term { form := .reference "$.name" } none none] } ] }

private def ageTm : TriplesMap :=
  { id := "http://e.org/tm/age"
  , source := { path := "people.json", iterator := some "$[*]",
                refFormulation := "http://w3id.org/rml/JSONPath" }
  , subject := { form := .constant (.iri (iriW "http://e.org/p/1")) }
  , poms := [ { predicates := [{ form := .constant (.iri (iriW "http://e.org/age")) }]
              , objects := [.term { form := .reference "$.id" } none none] } ] }

private def vs : VirtualSource :=
  { mapping := [nameTm, ageTm], docs := [("people.json", doc)] }

/-! ### The unbound scan returns every triple both maps generate -/

#guard (rmlSolve vs patternBoundAll).length == 6

/-! ### Structural narrowing drops a map by its CONSTANT predicate,
without reading a record -/

#guard (vs.mapping.filter (triplesMapCouldMatch { p := some (iriW "http://e.org/name") })).length == 1
#guard (vs.mapping.filter (triplesMapCouldMatch { p := some (iriW "http://e.org/age") })).length == 1
#guard (vs.mapping.filter (triplesMapCouldMatch { p := some (iriW "http://e.org/nope") })).length == 0
#guard rmlSolve vs { p := some (iriW "http://e.org/nope") } == []

/-! ### Structural narrowing drops a map by its CONSTANT subject -/

#guard (vs.mapping.filter
          (triplesMapCouldMatch { s := some (.iri (iriW "http://e.org/p/2")) })).length == 1

/-! ### Record-level pushdown iterates FEWER records than the unbound
scan — the property the whole module exists for.

`nameTm`'s subject is a template, so structural narrowing cannot rule it
out; the probe evaluates the subject alone and drops two of the three
records. -/

#guard rmlSolveTrace vs patternBoundAll == [("http://e.org/tm/name", 3), ("http://e.org/tm/age", 3)]
#guard recordsConsideredForMap vs { s := some (.iri (iriW "http://e.org/p/2")) } nameTm == 1
#guard recordsConsideredForMap vs patternBoundAll nameTm == 3

/-! ### The pushdown does not change the ANSWER, only the work

Every bound solve equals the unbound solve filtered by the same bound.
That is the safety property the narrowing has to satisfy. -/

private def pushdownIsInvisible (b : PatternBound) : Bool :=
  rmlSolve vs b == dedupeTriples (tripleMatchesBound b (rmlSolve vs patternBoundAll))

#guard pushdownIsInvisible patternBoundAll
#guard pushdownIsInvisible { s := some (.iri (iriW "http://e.org/p/2")) }
#guard pushdownIsInvisible { s := some (.iri (iriW "http://e.org/p/1")) }
#guard pushdownIsInvisible { p := some (iriW "http://e.org/name") }
#guard pushdownIsInvisible { p := some (iriW "http://e.org/age") }
#guard pushdownIsInvisible { o := some (.literal (Literal.string "Bob")) }
#guard pushdownIsInvisible { s := some (.iri (iriW "http://e.org/p/9")) }

/-! ### And it is not vacuous: the bound solves really do return rows -/

#guard (rmlSolve vs { s := some (.iri (iriW "http://e.org/p/2")) }).length == 1
#guard (rmlSolve vs { p := some (iriW "http://e.org/name") }).length == 3

/-! ### The record index survives the pushdown

A blank-node subject map labels its subject from the record's index. The
label a bound query returns must be the label the unbound query
returned for the same record — this is
<https://github.com/danbri/factoidal/issues/558>, which the F\* module
gets wrong by re-indexing the filtered list.

`bnodeTm` gives record 2 (index 1) the label `httpeorgtmbnoder1`. A
query bound to that label must find it. Under the F\* rule the surviving
record would be renumbered to index 0 and the label would move. -/

private def bnodeTm : TriplesMap :=
  { id := "http://e.org/tm/bnode"
  , source := { path := "people.json", iterator := some "$[*]",
                refFormulation := "http://w3id.org/rml/JSONPath" }
  , subject := { form := .unknown, termType := some .blankNode }
  , poms := [ { predicates := [{ form := .constant (.iri (iriW "http://e.org/name")) }]
              , objects := [.term { form := .reference "$.name" } none none] } ] }

private def bvs : VirtualSource :=
  { mapping := [bnodeTm], docs := [("people.json", doc)] }

#guard (rmlSolve bvs patternBoundAll).map (fun t => match t.s with
          | .bnode b => b | _ => "?") == ["httpeorgtmbnoder0", "httpeorgtmbnoder1", "httpeorgtmbnoder2"]

#guard (rmlSolve bvs { s := some (.bnode "httpeorgtmbnoder1") }).map
          (fun t => match t.o with | .literal l => l.val.lexicalForm | _ => "?") == ["Bob"]

/-! Under the F\* rule this would return `Alice` — the third record,
renumbered — or nothing. The check above is what makes the divergence a
pinned decision rather than an accident. -/

#guard (rmlSolve bvs { s := some (.bnode "httpeorgtmbnoder2") }).map
          (fun t => match t.o with | .literal l => l.val.lexicalForm | _ => "?") == ["Alice"]

/-! ### Duplicate records generate one triple, not two -/

private def dupDoc : Json :=
  .array [ .object [("id", .string "1"), ("name", .string "Alice")]
       , .object [("id", .string "1"), ("name", .string "Alice")] ]

private def dvs : VirtualSource :=
  { mapping := [nameTm], docs := [("people.json", dupDoc)] }

#guard (rmlSolve dvs patternBoundAll).length == 1

/-! ### A source path with no document yields no rows, rather than
failing -/

#guard rmlSolve { mapping := [nameTm], docs := [] } patternBoundAll == []

/-! ### The capability record agrees with `rmlSolve` -/

#guard (capsOfRmlSource vs).countExact patternBoundAll == 6
#guard (capsOfRmlSource vs).estimate patternBoundAll == 6
#guard (capsOfRmlSource vs).solveLimited patternBoundAll 2 == (rmlSolve vs patternBoundAll).take 2
#guard (capsOfRmlSource vs).predicatePresent (iriW "http://e.org/name")
#guard !(capsOfRmlSource vs).predicatePresent (iriW "http://e.org/nope")
#guard !(capsOfRmlSource vs).flags.supportsNamedGraphs

end Checks

end L4Factoidal.RML
