#!/bin/bash
# Generate W3C test results HTML report
# Usage: ./generate-report.sh [--run]
#   --run   Run tests first (default: use existing w3c_results.log)
#   Without --run, reads from ocaml-output/w3c_results.log
#
# Output: ../../docs/test-results/index.html

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OCAML_DIR="$SCRIPT_DIR/ocaml-output"
OUTPUT_DIR="$SCRIPT_DIR/../../docs/test-results"
SPARQL_LOG="$OCAML_DIR/sparql_results.log"
RDF_LOG="$OCAML_DIR/rdf_results.log"

mkdir -p "$OUTPUT_DIR"

if [ "$1" = "--run" ]; then
    echo "Running SPARQL tests..."
    cd "$OCAML_DIR"
    ./w3c_runner 2>&1 | tee "$SPARQL_LOG"
    echo ""
    echo "Running RDF tests..."
    ./w3c_runner --rdf 2>&1 | tee "$RDF_LOG"
    cd "$SCRIPT_DIR"
elif [ -f "$OCAML_DIR/w3c_results.log" ] && [ ! -f "$SPARQL_LOG" ]; then
    # Split combined log if only w3c_results.log exists (from build-ocaml.sh)
    echo "Splitting w3c_results.log into SPARQL and RDF logs..."
    # SPARQL section ends at the first "=== W3C RDF" line
    sed -n '1,/^=== W3C RDF/p' "$OCAML_DIR/w3c_results.log" | head -n -1 > "$SPARQL_LOG"
    sed -n '/^=== W3C RDF/,$p' "$OCAML_DIR/w3c_results.log" > "$RDF_LOG"
fi

if [ ! -f "$SPARQL_LOG" ] || [ ! -f "$RDF_LOG" ]; then
    echo "No test results found. Run with --run or run build-ocaml.sh first."
    exit 1
fi

# Extract per-suite lines and totals
SPARQL_SUITES=$(grep "^  " "$SPARQL_LOG" | grep -E "pass:|fail:" || true)
RDF_SUITES=$(grep "^  " "$RDF_LOG" | grep -E "pass:|fail:" || true)

SPARQL_TOTAL=$(grep "^TOTAL:" "$SPARQL_LOG" || echo "TOTAL: see log")
RDF_TOTAL=$(grep "^TOTAL:" "$RDF_LOG" || echo "TOTAL: see log")

# Compute aggregate numbers for summary
SPARQL_PASS=$(echo "$SPARQL_SUITES" | grep -oP 'pass:\K\d+' | awk '{s+=$1}END{print s+0}')
SPARQL_FAIL=$(echo "$SPARQL_SUITES" | grep -oP 'fail:\K\d+' | awk '{s+=$1}END{print s+0}')
SPARQL_SKIP=$(echo "$SPARQL_SUITES" | grep -oP 'skip:\K\d+' | awk '{s+=$1}END{print s+0}')
RDF_PASS=$(echo "$RDF_SUITES" | grep -oP 'pass:\K\d+' | awk '{s+=$1}END{print s+0}')
RDF_FAIL=$(echo "$RDF_SUITES" | grep -oP 'fail:\K\d+' | awk '{s+=$1}END{print s+0}')

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
GIT_SHA=$(git -C "$SCRIPT_DIR" rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_BRANCH=$(git -C "$SCRIPT_DIR" branch --show-current 2>/dev/null || echo "unknown")

cat > "$OUTPUT_DIR/index.html" << HTMLEOF
<!DOCTYPE html>
<html>
<head>
  <title>Factoidal W3C Test Results</title>
  <meta charset="utf-8">
  <style>
    body { font-family: system-ui, -apple-system, sans-serif; max-width: 800px; margin: 2em auto; padding: 0 1em; line-height: 1.6; color: #333; }
    h1 { border-bottom: 2px solid #2d6a4f; padding-bottom: 0.3em; }
    h2 { margin-top: 1.8em; }
    a { color: #2d6a4f; }
    nav { margin-bottom: 2em; font-size: 0.9em; }
    nav a { margin-right: 1.2em; }
    .summary { background: #f0f7f4; border: 1px solid #2d6a4f; border-radius: 6px; padding: 1em 1.5em; margin: 1em 0; }
    .summary .numbers { font-size: 1.3em; font-weight: bold; }
    .pass { color: #2d6a4f; }
    .fail { color: #c0392b; }
    .skip { color: #7f8c8d; }
    pre { background: #f8f8f8; padding: 1em; overflow-x: auto; border-radius: 4px; border: 1px solid #ddd; font-size: 0.85em; }
    .meta { color: #666; font-size: 0.85em; margin-bottom: 2em; }
    footer { margin-top: 3em; border-top: 1px solid #ddd; padding-top: 1em; font-size: 0.85em; color: #666; }
  </style>
</head>
<body>
<nav>
  <a href="/factoidal/">Home</a>
  <a href="/factoidal/test-results/">Test Results</a>
  <a href="https://github.com/danbri/factoidal">GitHub</a>
</nav>
<h1>W3C Test Results</h1>
<p class="meta">Generated: ${TIMESTAMP} &middot; Commit: <code>${GIT_SHA}</code> &middot; Branch: <code>${GIT_BRANCH}</code></p>

<div class="summary">
  <div class="numbers">
    SPARQL 1.1: <span class="pass">${SPARQL_PASS} pass</span>, <span class="fail">${SPARQL_FAIL} fail</span>, <span class="skip">${SPARQL_SKIP} skip</span>
  </div>
  <div class="numbers">
    RDF 1.1: <span class="pass">${RDF_PASS} pass</span>, <span class="fail">${RDF_FAIL} fail</span>
  </div>
</div>

<h2>SPARQL 1.1 Per-Suite</h2>
<pre>
${SPARQL_SUITES}
</pre>

<h2>RDF 1.1 Per-Suite</h2>
<pre>
${RDF_SUITES}
</pre>

<footer>
  Factoidal &mdash; verified RDF/SPARQL from F*.
  Report generated by <code>generate-report.sh</code>.
</footer>
</body></html>
HTMLEOF

echo ""
echo "Report generated: $OUTPUT_DIR/index.html"
echo "  SPARQL: ${SPARQL_PASS} pass, ${SPARQL_FAIL} fail, ${SPARQL_SKIP} skip"
echo "  RDF:    ${RDF_PASS} pass, ${RDF_FAIL} fail"
echo "  Commit: ${GIT_SHA} (${GIT_BRANCH})"
