#!/usr/bin/env bash
# tests/vc20-api/run.sh — run the ALREADY-vendored w3c/vc-data-model-2.0
# -test-suite (third_party/testing/vc/) mocha suite's issuer/verifier
# HTTP tests against bin/vc-api-shim/server.mjs (task #88, canivc.com
# community-compatibility integration).
#
# This is a SEPARATE row from the existing vc_stage1 suite
# (bin/vc-runner + .github/test-suites/vc.yaml): vc_stage1 runs the
# same vendored fixtures directly through VC.Credential.fst's
# structural checker (120 fixtures, no HTTP, no signing). This suite
# instead drives the mocha suite's OWN HTTP issuer/verifier tests
# (issue a credential, then assert required properties + rejection of
# malformed inputs) against the shim — a different, complementary
# measurement. Do not conflate the two scores.
#
# Requires: `npm install` already run in third_party/testing/vc.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SUITE_DIR="$REPO_ROOT/third_party/testing/vc"
PORT="${VC20_API_PORT:-40448}"
RESULT_JSON="$REPO_ROOT/docs/test-results/by-suite/vc20-api.json"
MOCHA_JSON="$(mktemp)"
SHIM_LOG="$(mktemp)"

if [[ ! -d "$SUITE_DIR/node_modules" ]]; then
  echo "FAIL: $SUITE_DIR/node_modules missing — run: (cd $SUITE_DIR && npm install)"
  exit 1
fi

cleanup() {
  if [[ -n "${SHIM_PID:-}" ]] && kill -0 "$SHIM_PID" 2>/dev/null; then
    kill "$SHIM_PID" 2>/dev/null || true
    wait "$SHIM_PID" 2>/dev/null || true
  fi
  rm -f "$MOCHA_JSON" "$SHIM_LOG"
}
trap cleanup EXIT

node "$REPO_ROOT/bin/vc-api-shim/server.mjs" --port "$PORT" > "$SHIM_LOG" 2>&1 &
SHIM_PID=$!
for _ in $(seq 1 50); do
  grep -q "vc-api-shim listening on" "$SHIM_LOG" 2>/dev/null && break
  sleep 0.2
done
if ! grep -q "vc-api-shim listening on" "$SHIM_LOG" 2>/dev/null; then
  echo "FAIL: shim did not start"
  cat "$SHIM_LOG"
  exit 1
fi
ISSUER_DID="$(grep -o 'issuer=did:key:[A-Za-z0-9]*' "$SHIM_LOG" | head -1 | sed 's/issuer=//')"

cat > "$SUITE_DIR/localConfig.cjs" << EOF
/*! Generated by tests/vc20-api/run.sh (task #88). Not committed. */
const baseUrl = process.env.BASE_URL || 'http://localhost:$PORT';
module.exports = {
  settings: { enableInteropTests: false, testAllImplementations: false },
  implementations: [{
    name: 'Factoidal',
    implementation: 'Factoidal VC-API shim',
    issuers: [{
      id: '$ISSUER_DID',
      endpoint: \`\${baseUrl}/credentials/issue\`,
      supports: { vc: ['2.0'] },
      tags: ['vc2.0']
    }],
    verifiers: [{
      id: '$ISSUER_DID',
      endpoint: \`\${baseUrl}/credentials/verify\`,
      tags: ['vc2.0']
    }],
    vpVerifiers: [{
      id: '$ISSUER_DID',
      endpoint: \`\${baseUrl}/presentations/verify\`,
      tags: ['vc2.0']
    }]
  }]
};
EOF

cd "$SUITE_DIR"
MOCHA_RC=0
timeout 300 npx mocha \
  tests/1.03-conformance.js tests/4.03-contexts.js tests/4.04-identifiers.js \
  tests/4.05-types.js tests/4.06-names-and-descriptions.js tests/4.07-issuer.js \
  tests/4.08-credential-subject.js tests/4.09-validity-period.js tests/4.10-status.js \
  tests/4.11-data-schemas.js tests/4.13-verifiable-presentations.js \
  tests/4.13.2-envelopes.js tests/5-advanced-concepts.js tests/7-algorithms.js \
  --timeout 15000 --reporter json > "$MOCHA_JSON" 2>/dev/null || MOCHA_RC=$?

python3 - "$MOCHA_JSON" "$RESULT_JSON" "$MOCHA_RC" << 'PYEOF'
import json, sys, datetime

mocha_path, out_path, mocha_rc = sys.argv[1], sys.argv[2], int(sys.argv[3])

try:
    with open(mocha_path) as f:
        d = json.load(f)
except Exception as e:
    print(f"FAIL: could not parse mocha JSON reporter output: {e}")
    sys.exit(1)

stats = d["stats"]
failures = [
    {"title": f["fullTitle"], "message": (f.get("err") or {}).get("message", "")}
    for f in d["failures"]
]

result = {
    "spec": "https://w3c.github.io/vc-data-model-2.0-test-suite/",
    "suite": "vc-data-model-2.0 (issuer/verifier HTTP suite, via shim)",
    "runner": "tests/vc20-api/run.sh",
    "retrieved_at": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "pass": stats["passes"],
    "fail": stats["failures"],
    "skip": stats.get("pending", 0),
    "total": stats["tests"],
    "present": True,
    "gap_summary": "Track A3 (2026-07-13): wired POST /presentations/verify (structural check via the same vcCheckCredential export, then eddsa-rdfc-2022 Data Integrity proof verification over the VP's own top-level proof). Remaining 8 fails are two families, neither a wiring gap: relatedResource digest/id checks (Advanced Concepts, 5 tests) VC.Credential.fst does not implement at all; and 3 VP tests whose fixture embeds a `verifiableCredential` (@container:@graph in the VCDM v2 context) -- the shim's JSON-LD/RDF-dataset builder drops that named-graph subtree entirely during canonicalization (confirmed: canonicalizing a VP with an embedded credential yields ONLY the top-level `type` triple), so the reconstructed signature input never matches what the real signer produced. This is a JSON-LD named-graph expansion gap, not a VC.Credential.fst structural-check gap -- out of scope for a wiring task. This is a separate, complementary measurement from vc_stage1 (.github/test-suites/vc.yaml), which runs the SAME vendored fixtures directly through VC.Credential.fst's structural checker, no HTTP.",
    "failures": failures,
}

with open(out_path, "w") as f:
    json.dump(result, f, indent=2)
    f.write("\n")

print(f"vc20-api: {stats['passes']} pass, {stats['failures']} fail (out of {stats['tests']}) -> {out_path}")
PYEOF
