/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-compilation -warn-error -9-11-15 -add-include "krml/internal/compat.h" -tmpdir /tmp/rdf-c-output RDF.Graph.Executable.fst
  F* version: <unknown>
  KaRaMeL version: d7a8f9ec
 */

#include "internal/FStar.h"

extern krml_checked_int_t FStar_UInt32_v(uint32_t x);

extern uint32_t FStar_Char_u32_of_char(FStar_Char_char uu___);

krml_checked_int_t FStar_Char_int_of_char(FStar_Char_char c)
{
  return FStar_UInt32_v(FStar_Char_u32_of_char(c));
}

