/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-compilation -skip-makefiles -tmpdir c-output -warn-error +2 -bundle RDF.Format+SPARQL.JSON.Escape+SPARQL.HTTP.StaticFiles+SPARQL.HTTP.QueriesIndex=*[rename=Factoidal_Pilot] krml-output/groupA/out.krml
  F* version: <unknown>
  KaRaMeL version: 11bb8e1ac2f720fb7144b9b768c7251526caa149
 */

#ifndef Factoidal_Pilot_H
#define Factoidal_Pilot_H

#include "krmllib.h"

#define Prims_Nil 0
#define Prims_Cons 1

typedef uint8_t Prims_list__FStar_Char_char_tags;

#define RDF_Format_NT 0
#define RDF_Format_Turtle 1
#define RDF_Format_NQuads 2
#define RDF_Format_TriG 3
#define RDF_Format_RDFXML 4
#define RDF_Format_JSONLD 5

typedef uint8_t RDF_Format_rdf_format;

bool RDF_Format_uu___is_NT(RDF_Format_rdf_format projectee);

bool RDF_Format_uu___is_Turtle(RDF_Format_rdf_format projectee);

bool RDF_Format_uu___is_NQuads(RDF_Format_rdf_format projectee);

bool RDF_Format_uu___is_TriG(RDF_Format_rdf_format projectee);

bool RDF_Format_uu___is_RDFXML(RDF_Format_rdf_format projectee);

bool RDF_Format_uu___is_JSONLD(RDF_Format_rdf_format projectee);

extern RDF_Format_rdf_format RDF_Format_rdf_format_default;

#define FStar_Pervasives_Native_None 0
#define FStar_Pervasives_Native_Some 1

typedef uint8_t FStar_Pervasives_Native_option__RDF_Format_rdf_format_tags;

typedef struct FStar_Pervasives_Native_option__RDF_Format_rdf_format_s
{
  FStar_Pervasives_Native_option__RDF_Format_rdf_format_tags tag;
  RDF_Format_rdf_format v;
}
FStar_Pervasives_Native_option__RDF_Format_rdf_format;

extern bool __eq__Prims_string(Prims_string x, Prims_string y);

FStar_Pervasives_Native_option__RDF_Format_rdf_format
RDF_Format_format_of_extension(Prims_string ext);

FStar_Pervasives_Native_option__RDF_Format_rdf_format
RDF_Format_format_of_string(Prims_string s);

Prims_string RDF_Format_format_name(RDF_Format_rdf_format f);

RDF_Format_rdf_format RDF_Format_detect_format_or_default(Prims_string extension);

FStar_Char_char SPARQL_JSON_Escape_hex_digit_lc(krml_checked_int_t n);

bool SPARQL_JSON_Escape_json_special(krml_checked_int_t b);

Prims_string SPARQL_JSON_Escape_escape_string_of_byte(krml_checked_int_t b);

Prims_string
SPARQL_JSON_Escape_walk_runs(
  Prims_string s,
  krml_checked_int_t len,
  krml_checked_int_t run_start,
  krml_checked_int_t pos,
  Prims_string acc
);

Prims_string SPARQL_JSON_Escape_json_escape(Prims_string s);

bool SPARQL_HTTP_StaticFiles_ends_with(Prims_string s, Prims_string suf);

Prims_string SPARQL_HTTP_StaticFiles_content_type_for_path(Prims_string path);

bool SPARQL_HTTP_StaticFiles_contains_dotdot_at(Prims_string s, krml_checked_int_t i);

bool SPARQL_HTTP_StaticFiles_path_has_dotdot(Prims_string p);

typedef struct SPARQL_HTTP_QueriesIndex_query_entry_s
{
  Prims_string qe_group;
  Prims_string qe_key;
  Prims_string qe_label;
  Prims_string qe_body;
}
SPARQL_HTTP_QueriesIndex_query_entry;

typedef struct Prims_list__SPARQL_HTTP_QueriesIndex_query_entry_s
Prims_list__SPARQL_HTTP_QueriesIndex_query_entry;

typedef struct Prims_list__SPARQL_HTTP_QueriesIndex_query_entry_s
{
  Prims_list__FStar_Char_char_tags tag;
  SPARQL_HTTP_QueriesIndex_query_entry hd;
  Prims_list__SPARQL_HTTP_QueriesIndex_query_entry *tl;
}
Prims_list__SPARQL_HTTP_QueriesIndex_query_entry;

typedef struct SPARQL_HTTP_QueriesIndex_query_group_s
{
  Prims_string qg_name;
  Prims_list__SPARQL_HTTP_QueriesIndex_query_entry *qg_entries;
}
SPARQL_HTTP_QueriesIndex_query_group;

Prims_string SPARQL_HTTP_QueriesIndex_strip_rq_suffix(Prims_string s);

Prims_string
SPARQL_HTTP_QueriesIndex_parliament_label(Prims_string group, Prims_string filename);

Prims_string
SPARQL_HTTP_QueriesIndex_render_entry_chars(SPARQL_HTTP_QueriesIndex_query_entry e);

Prims_string
SPARQL_HTTP_QueriesIndex_render_entries_acc(
  Prims_list__SPARQL_HTTP_QueriesIndex_query_entry *entries,
  bool first,
  Prims_string acc
);

Prims_string
SPARQL_HTTP_QueriesIndex_render_queries_index(
  Prims_list__SPARQL_HTTP_QueriesIndex_query_entry *entries
);

typedef struct Prims_list__SPARQL_HTTP_QueriesIndex_query_group_s
Prims_list__SPARQL_HTTP_QueriesIndex_query_group;

typedef struct Prims_list__SPARQL_HTTP_QueriesIndex_query_group_s
{
  Prims_list__FStar_Char_char_tags tag;
  SPARQL_HTTP_QueriesIndex_query_group hd;
  Prims_list__SPARQL_HTTP_QueriesIndex_query_group *tl;
}
Prims_list__SPARQL_HTTP_QueriesIndex_query_group;

Prims_list__SPARQL_HTTP_QueriesIndex_query_entry
*SPARQL_HTTP_QueriesIndex_flatten_groups(
  Prims_list__SPARQL_HTTP_QueriesIndex_query_group *groups
);


#define Factoidal_Pilot_H_DEFINED
#endif /* Factoidal_Pilot_H */
