/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-compilation -skip-makefiles -tmpdir c-output -warn-error +2 -bundle RDF.Format+SPARQL.JSON.Escape+SPARQL.HTTP.StaticFiles+SPARQL.HTTP.QueriesIndex=*[rename=Factoidal_Pilot] krml-output/groupA/out.krml
  F* version: <unknown>
  KaRaMeL version: 11bb8e1ac2f720fb7144b9b768c7251526caa149
 */

#include "internal/Factoidal_Pilot.h"

extern krml_checked_int_t Prims_op_Division(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Subtraction(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Addition(krml_checked_int_t x, krml_checked_int_t y);

extern krml_checked_int_t Prims_op_Modulus(krml_checked_int_t x, krml_checked_int_t y);

extern bool Prims_op_GreaterThan(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_GreaterThanOrEqual(krml_checked_int_t x0, krml_checked_int_t x1);

extern bool Prims_op_LessThan(krml_checked_int_t x0, krml_checked_int_t x1);

extern Prims_string Prims_strcat(Prims_string x0, Prims_string x1);

extern uint32_t FStar_UInt32_uint_to_t(krml_checked_int_t x);

extern FStar_Char_char FStar_Char_char_of_u32(uint32_t uu___);

static FStar_Char_char char_of_int(krml_checked_int_t i)
{
  return FStar_Char_char_of_u32(FStar_UInt32_uint_to_t(i));
}

extern krml_checked_int_t Parser_FastString_fs_byte_length(Prims_string uu___);

extern krml_checked_int_t Parser_FastString_fs_byte_at(Prims_string s, krml_checked_int_t i);

extern Prims_string
Parser_FastString_fs_byte_sub(Prims_string s, krml_checked_int_t start, krml_checked_int_t len);

typedef struct list__FStar_Char_char_s list__FStar_Char_char;

typedef struct list__FStar_Char_char_s
{
  Prims_list__FStar_Char_char_tags tag;
  FStar_Char_char hd;
  list__FStar_Char_char *tl;
}
list__FStar_Char_char;

extern Prims_string FStar_String_string_of_list(list__FStar_Char_char *uu___);

extern krml_checked_int_t FStar_String_strlen(Prims_string s);

extern Prims_string FStar_String_lowercase(Prims_string uu___);

extern Prims_string
FStar_String_sub(Prims_string s, krml_checked_int_t i, krml_checked_int_t l);

bool RDF_Format_uu___is_NT(RDF_Format_rdf_format projectee)
{
  switch (projectee)
  {
    case RDF_Format_NT:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool RDF_Format_uu___is_Turtle(RDF_Format_rdf_format projectee)
{
  switch (projectee)
  {
    case RDF_Format_Turtle:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool RDF_Format_uu___is_NQuads(RDF_Format_rdf_format projectee)
{
  switch (projectee)
  {
    case RDF_Format_NQuads:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool RDF_Format_uu___is_TriG(RDF_Format_rdf_format projectee)
{
  switch (projectee)
  {
    case RDF_Format_TriG:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool RDF_Format_uu___is_RDFXML(RDF_Format_rdf_format projectee)
{
  switch (projectee)
  {
    case RDF_Format_RDFXML:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool RDF_Format_uu___is_JSONLD(RDF_Format_rdf_format projectee)
{
  switch (projectee)
  {
    case RDF_Format_JSONLD:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

RDF_Format_rdf_format RDF_Format_rdf_format_default = RDF_Format_Turtle;

FStar_Pervasives_Native_option__RDF_Format_rdf_format
RDF_Format_format_of_extension(Prims_string ext)
{
  Prims_string lo = FStar_String_lowercase(ext);
  if (__eq__Prims_string(lo, ".nt"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_NT
        }
      );
  else if (__eq__Prims_string(lo, ".ntriples"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_NT
        }
      );
  else if (__eq__Prims_string(lo, ".ttl"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_Turtle
        }
      );
  else if (__eq__Prims_string(lo, ".turtle"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_Turtle
        }
      );
  else if (__eq__Prims_string(lo, ".nq"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_NQuads
        }
      );
  else if (__eq__Prims_string(lo, ".nquads"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_NQuads
        }
      );
  else if (__eq__Prims_string(lo, ".trig"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_TriG
        }
      );
  else if (__eq__Prims_string(lo, ".rdf"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_RDFXML
        }
      );
  else if (__eq__Prims_string(lo, ".xml"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_RDFXML
        }
      );
  else if (__eq__Prims_string(lo, ".rdfxml"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_RDFXML
        }
      );
  else if (__eq__Prims_string(lo, ".owl"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_RDFXML
        }
      );
  else if (__eq__Prims_string(lo, ".jsonld"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_JSONLD
        }
      );
  else if (__eq__Prims_string(lo, ".json-ld"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_JSONLD
        }
      );
  else
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_None
        }
      );
}

FStar_Pervasives_Native_option__RDF_Format_rdf_format
RDF_Format_format_of_string(Prims_string s)
{
  Prims_string lo = FStar_String_lowercase(s);
  if (__eq__Prims_string(lo, "ntriples"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_NT
        }
      );
  else if (__eq__Prims_string(lo, "nt"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_NT
        }
      );
  else if (__eq__Prims_string(lo, "n-triples"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_NT
        }
      );
  else if (__eq__Prims_string(lo, "turtle"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_Turtle
        }
      );
  else if (__eq__Prims_string(lo, "ttl"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_Turtle
        }
      );
  else if (__eq__Prims_string(lo, "nquads"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_NQuads
        }
      );
  else if (__eq__Prims_string(lo, "nq"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_NQuads
        }
      );
  else if (__eq__Prims_string(lo, "n-quads"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_NQuads
        }
      );
  else if (__eq__Prims_string(lo, "trig"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_TriG
        }
      );
  else if (__eq__Prims_string(lo, "rdfxml"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_RDFXML
        }
      );
  else if (__eq__Prims_string(lo, "rdf/xml"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_RDFXML
        }
      );
  else if (__eq__Prims_string(lo, "rdf"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_RDFXML
        }
      );
  else if (__eq__Prims_string(lo, "xml"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_RDFXML
        }
      );
  else if (__eq__Prims_string(lo, "jsonld"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_JSONLD
        }
      );
  else if (__eq__Prims_string(lo, "json-ld"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_JSONLD
        }
      );
  else if (__eq__Prims_string(lo, "application/ld+json"))
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_Some,
          .v = RDF_Format_JSONLD
        }
      );
  else
    return
      (
        (FStar_Pervasives_Native_option__RDF_Format_rdf_format){
          .tag = FStar_Pervasives_Native_None
        }
      );
}

Prims_string RDF_Format_format_name(RDF_Format_rdf_format f)
{
  switch (f)
  {
    case RDF_Format_NT:
      {
        return "N-Triples";
      }
    case RDF_Format_Turtle:
      {
        return "Turtle";
      }
    case RDF_Format_NQuads:
      {
        return "N-Quads";
      }
    case RDF_Format_TriG:
      {
        return "TriG";
      }
    case RDF_Format_RDFXML:
      {
        return "RDF/XML";
      }
    case RDF_Format_JSONLD:
      {
        return "JSON-LD (expanded form)";
      }
    default:
      {
        KRML_HOST_EPRINTF("KaRaMeL incomplete match at %s:%d\n", __FILE__, __LINE__);
        KRML_HOST_EXIT(253U);
      }
  }
}

RDF_Format_rdf_format RDF_Format_detect_format_or_default(Prims_string extension)
{
  FStar_Pervasives_Native_option__RDF_Format_rdf_format
  scrut = RDF_Format_format_of_extension(extension);
  if (scrut.tag == FStar_Pervasives_Native_Some)
    return scrut.v;
  else if (scrut.tag == FStar_Pervasives_Native_None)
    return RDF_Format_rdf_format_default;
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

FStar_Char_char SPARQL_JSON_Escape_hex_digit_lc(krml_checked_int_t n)
{
  if (Prims_op_LessThan(n, 10))
    return char_of_int(Prims_op_Addition(0x30, n));
  else if (Prims_op_LessThan(n, 16))
    return char_of_int(Prims_op_Addition(0x61, Prims_op_Subtraction(n, 10)));
  else
    return char_of_int(0x30);
}

bool SPARQL_JSON_Escape_json_special(krml_checked_int_t b)
{
  return Prims_op_LessThan(b, 0x20) || b == 0x22 || b == 0x5C;
}

Prims_string SPARQL_JSON_Escape_escape_string_of_byte(krml_checked_int_t b)
{
  if (b == 0x5C)
    return "\\\\";
  else if (b == 0x22)
    return "\\\"";
  else if (b == 0x0A)
    return "\\n";
  else if (b == 0x0D)
    return "\\r";
  else if (b == 0x09)
    return "\\t";
  else if (b == 0x08)
    return "\\b";
  else if (b == 0x0C)
    return "\\f";
  else
  {
    krml_checked_int_t n3 = Prims_op_Modulus(b, 16);
    krml_checked_int_t n2 = Prims_op_Modulus(Prims_op_Division(b, 16), 16);
    list__FStar_Char_char *buf = KRML_HOST_MALLOC(sizeof (list__FStar_Char_char));
    if (buf != NULL)
      buf[0U] = ((list__FStar_Char_char){ .tag = Prims_Nil });
    list__FStar_Char_char *buf0 = KRML_HOST_MALLOC(sizeof (list__FStar_Char_char));
    if (buf0 != NULL)
      buf0[0U] =
        (
          (list__FStar_Char_char){
            .tag = Prims_Cons,
            .hd = SPARQL_JSON_Escape_hex_digit_lc(n3),
            .tl = buf
          }
        );
    list__FStar_Char_char *buf1 = KRML_HOST_MALLOC(sizeof (list__FStar_Char_char));
    if (buf1 != NULL)
      buf1[0U] =
        (
          (list__FStar_Char_char){
            .tag = Prims_Cons,
            .hd = SPARQL_JSON_Escape_hex_digit_lc(n2),
            .tl = buf0
          }
        );
    list__FStar_Char_char *buf2 = KRML_HOST_MALLOC(sizeof (list__FStar_Char_char));
    if (buf2 != NULL)
      buf2[0U] = ((list__FStar_Char_char){ .tag = Prims_Cons, .hd = char_of_int(0x30), .tl = buf1 });
    list__FStar_Char_char *buf3 = KRML_HOST_MALLOC(sizeof (list__FStar_Char_char));
    if (buf3 != NULL)
      buf3[0U] = ((list__FStar_Char_char){ .tag = Prims_Cons, .hd = char_of_int(0x30), .tl = buf2 });
    list__FStar_Char_char *buf4 = KRML_HOST_MALLOC(sizeof (list__FStar_Char_char));
    if (buf4 != NULL)
      buf4[0U] = ((list__FStar_Char_char){ .tag = Prims_Cons, .hd = char_of_int(0x75), .tl = buf3 });
    list__FStar_Char_char *buf5 = KRML_HOST_MALLOC(sizeof (list__FStar_Char_char));
    if (buf5 != NULL)
      buf5[0U] = ((list__FStar_Char_char){ .tag = Prims_Cons, .hd = char_of_int(0x5C), .tl = buf4 });
    return FStar_String_string_of_list(buf5);
  }
}

Prims_string
SPARQL_JSON_Escape_walk_runs(
  Prims_string s,
  krml_checked_int_t len,
  krml_checked_int_t run_start,
  krml_checked_int_t pos,
  Prims_string acc
)
{
  if (Prims_op_GreaterThanOrEqual(pos, len))
    if (Prims_op_GreaterThan(pos, run_start))
      return
        Prims_strcat(acc,
          Parser_FastString_fs_byte_sub(s, run_start, Prims_op_Subtraction(pos, run_start)));
    else
      return acc;
  else
  {
    krml_checked_int_t b = Parser_FastString_fs_byte_at(s, pos);
    if (SPARQL_JSON_Escape_json_special(b))
    {
      Prims_string run;
      if (Prims_op_GreaterThan(pos, run_start))
        run = Parser_FastString_fs_byte_sub(s, run_start, Prims_op_Subtraction(pos, run_start));
      else
        run = "";
      return
        SPARQL_JSON_Escape_walk_runs(s,
          len,
          Prims_op_Addition(pos, 1),
          Prims_op_Addition(pos, 1),
          Prims_strcat(acc, Prims_strcat(run, SPARQL_JSON_Escape_escape_string_of_byte(b))));
    }
    else
      return SPARQL_JSON_Escape_walk_runs(s, len, run_start, Prims_op_Addition(pos, 1), acc);
  }
}

Prims_string SPARQL_JSON_Escape_json_escape(Prims_string s)
{
  krml_checked_int_t len = Parser_FastString_fs_byte_length(s);
  return SPARQL_JSON_Escape_walk_runs(s, len, 0, 0, "");
}

bool SPARQL_HTTP_StaticFiles_ends_with(Prims_string s, Prims_string suf)
{
  krml_checked_int_t lp = FStar_String_strlen(s);
  krml_checked_int_t ls = FStar_String_strlen(suf);
  if (Prims_op_GreaterThanOrEqual(lp, ls))
    return __eq__Prims_string(FStar_String_sub(s, Prims_op_Subtraction(lp, ls), ls), suf);
  else
    return false;
}

Prims_string SPARQL_HTTP_StaticFiles_content_type_for_path(Prims_string path)
{
  Prims_string p = FStar_String_lowercase(path);
  if
  (SPARQL_HTTP_StaticFiles_ends_with(p, ".html") || SPARQL_HTTP_StaticFiles_ends_with(p, ".htm"))
    return "text/html; charset=utf-8";
  else if (SPARQL_HTTP_StaticFiles_ends_with(p, ".css"))
    return "text/css; charset=utf-8";
  else if
  (SPARQL_HTTP_StaticFiles_ends_with(p, ".js") || SPARQL_HTTP_StaticFiles_ends_with(p, ".mjs"))
    return "application/javascript; charset=utf-8";
  else if (SPARQL_HTTP_StaticFiles_ends_with(p, ".json"))
    return "application/json; charset=utf-8";
  else if (SPARQL_HTTP_StaticFiles_ends_with(p, ".svg"))
    return "image/svg+xml; charset=utf-8";
  else if (SPARQL_HTTP_StaticFiles_ends_with(p, ".png"))
    return "image/png";
  else if
  (SPARQL_HTTP_StaticFiles_ends_with(p, ".jpg") || SPARQL_HTTP_StaticFiles_ends_with(p, ".jpeg"))
    return "image/jpeg";
  else if (SPARQL_HTTP_StaticFiles_ends_with(p, ".ico"))
    return "image/x-icon";
  else if
  (SPARQL_HTTP_StaticFiles_ends_with(p, ".txt") || SPARQL_HTTP_StaticFiles_ends_with(p, ".md"))
    return "text/plain; charset=utf-8";
  else if (SPARQL_HTTP_StaticFiles_ends_with(p, ".ttl"))
    return "text/turtle; charset=utf-8";
  else if (SPARQL_HTTP_StaticFiles_ends_with(p, ".nt"))
    return "application/n-triples; charset=utf-8";
  else if (SPARQL_HTTP_StaticFiles_ends_with(p, ".nq"))
    return "application/n-quads; charset=utf-8";
  else
    return "application/octet-stream";
}

bool SPARQL_HTTP_StaticFiles_contains_dotdot_at(Prims_string s, krml_checked_int_t i)
{
  krml_checked_int_t n = FStar_String_strlen(s);
  if (Prims_op_GreaterThan(Prims_op_Addition(i, 2), n))
    return false;
  else if (__eq__Prims_string(FStar_String_sub(s, i, 2), ".."))
    return true;
  else if (Prims_op_GreaterThan(Prims_op_Addition(i, 1), n))
    return false;
  else
    return SPARQL_HTTP_StaticFiles_contains_dotdot_at(s, Prims_op_Addition(i, 1));
}

bool SPARQL_HTTP_StaticFiles_path_has_dotdot(Prims_string p)
{
  return SPARQL_HTTP_StaticFiles_contains_dotdot_at(p, 0);
}

Prims_string SPARQL_HTTP_QueriesIndex_strip_rq_suffix(Prims_string s)
{
  krml_checked_int_t len = Parser_FastString_fs_byte_length(s);
  if (Prims_op_LessThan(len, 3))
    return s;
  else
  {
    krml_checked_int_t b0 = Parser_FastString_fs_byte_at(s, Prims_op_Subtraction(len, 3));
    krml_checked_int_t b1 = Parser_FastString_fs_byte_at(s, Prims_op_Subtraction(len, 2));
    krml_checked_int_t b2 = Parser_FastString_fs_byte_at(s, Prims_op_Subtraction(len, 1));
    if (b0 == 0x2E && b1 == 0x72 && b2 == 0x71)
      return Parser_FastString_fs_byte_sub(s, 0, Prims_op_Subtraction(len, 3));
    else
      return s;
  }
}

Prims_string
SPARQL_HTTP_QueriesIndex_parliament_label(Prims_string group, Prims_string filename)
{
  return
    Prims_strcat(group,
      Prims_strcat(" / ", SPARQL_HTTP_QueriesIndex_strip_rq_suffix(filename)));
}

Prims_string
SPARQL_HTTP_QueriesIndex_render_entry_chars(SPARQL_HTTP_QueriesIndex_query_entry e)
{
  return
    Prims_strcat("  {\"group\":\"",
      Prims_strcat(SPARQL_JSON_Escape_json_escape(e.qe_group),
        Prims_strcat("\",\"key\":\"",
          Prims_strcat(SPARQL_JSON_Escape_json_escape(e.qe_key),
            Prims_strcat("\",\"label\":\"",
              Prims_strcat(SPARQL_JSON_Escape_json_escape(e.qe_label),
                Prims_strcat("\",\"body\":\"",
                  Prims_strcat(SPARQL_JSON_Escape_json_escape(e.qe_body), "\"}"))))))));
}

Prims_string
SPARQL_HTTP_QueriesIndex_render_entries_acc(
  Prims_list__SPARQL_HTTP_QueriesIndex_query_entry *entries,
  bool first,
  Prims_string acc
)
{
  if (entries->tag == Prims_Nil)
    return acc;
  else if (entries->tag == Prims_Cons)
  {
    Prims_list__SPARQL_HTTP_QueriesIndex_query_entry *rest = entries->tl;
    SPARQL_HTTP_QueriesIndex_query_entry e = entries->hd;
    Prims_string sep = first ? "\n" : ",\n";
    Prims_string
    acc_ = Prims_strcat(acc, Prims_strcat(sep, SPARQL_HTTP_QueriesIndex_render_entry_chars(e)));
    return SPARQL_HTTP_QueriesIndex_render_entries_acc(rest, false, acc_);
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

Prims_string
SPARQL_HTTP_QueriesIndex_render_queries_index(
  Prims_list__SPARQL_HTTP_QueriesIndex_query_entry *entries
)
{
  Prims_string body = SPARQL_HTTP_QueriesIndex_render_entries_acc(entries, true, "");
  return Prims_strcat("[", Prims_strcat(body, "\n]\n"));
}

Prims_list__SPARQL_HTTP_QueriesIndex_query_entry
*FStar_List_Tot_Base_append__SPARQL_HTTP_QueriesIndex_query_entry(
  Prims_list__SPARQL_HTTP_QueriesIndex_query_entry *x,
  Prims_list__SPARQL_HTTP_QueriesIndex_query_entry *y
)
{
  if (x->tag == Prims_Nil)
    return y;
  else if (x->tag == Prims_Cons)
  {
    Prims_list__SPARQL_HTTP_QueriesIndex_query_entry *tl1 = x->tl;
    SPARQL_HTTP_QueriesIndex_query_entry a1 = x->hd;
    Prims_list__SPARQL_HTTP_QueriesIndex_query_entry
    *buf = KRML_HOST_MALLOC(sizeof (Prims_list__SPARQL_HTTP_QueriesIndex_query_entry));
    if (buf != NULL)
      buf[0U] =
        (
          (Prims_list__SPARQL_HTTP_QueriesIndex_query_entry){
            .tag = Prims_Cons,
            .hd = a1,
            .tl = FStar_List_Tot_Base_append__SPARQL_HTTP_QueriesIndex_query_entry(tl1, y)
          }
        );
    return buf;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static Prims_list__SPARQL_HTTP_QueriesIndex_query_entry
*op_At__SPARQL_HTTP_QueriesIndex_query_entry(
  Prims_list__SPARQL_HTTP_QueriesIndex_query_entry *x,
  Prims_list__SPARQL_HTTP_QueriesIndex_query_entry *y
)
{
  return FStar_List_Tot_Base_append__SPARQL_HTTP_QueriesIndex_query_entry(x, y);
}

Prims_list__SPARQL_HTTP_QueriesIndex_query_entry
*SPARQL_HTTP_QueriesIndex_flatten_groups(
  Prims_list__SPARQL_HTTP_QueriesIndex_query_group *groups
)
{
  if (groups->tag == Prims_Nil)
  {
    Prims_list__SPARQL_HTTP_QueriesIndex_query_entry
    *buf = KRML_HOST_MALLOC(sizeof (Prims_list__SPARQL_HTTP_QueriesIndex_query_entry));
    if (buf != NULL)
      buf[0U] = ((Prims_list__SPARQL_HTTP_QueriesIndex_query_entry){ .tag = Prims_Nil });
    return buf;
  }
  else if (groups->tag == Prims_Cons)
  {
    Prims_list__SPARQL_HTTP_QueriesIndex_query_group *rest = groups->tl;
    SPARQL_HTTP_QueriesIndex_query_group g = groups->hd;
    return
      op_At__SPARQL_HTTP_QueriesIndex_query_entry(g.qg_entries,
        SPARQL_HTTP_QueriesIndex_flatten_groups(rest));
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

