/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-compilation -warn-error -9-11-15 -add-include "krml/internal/compat.h" -tmpdir /tmp/rdf-c-output RDF.Graph.Executable.fst
  F* version: <unknown>
  KaRaMeL version: d7a8f9ec
 */

#ifndef FStar_H
#define FStar_H

#include "krmllib.h"

#include "krml/internal/compat.h"

typedef struct Prims_list__FStar_Char_char_s Prims_list__FStar_Char_char;

#define Prims_Nil 0
#define Prims_Cons 1

typedef uint8_t Prims_list__FStar_Char_char_tags;

typedef struct Prims_list__FStar_Char_char_s
{
  Prims_list__FStar_Char_char_tags tag;
  FStar_Char_char hd;
  Prims_list__FStar_Char_char *tl;
}
Prims_list__FStar_Char_char;

typedef struct Prims_list__Prims_string_s Prims_list__Prims_string;

typedef struct Prims_list__Prims_string_s
{
  Prims_list__FStar_Char_char_tags tag;
  Prims_string hd;
  Prims_list__Prims_string *tl;
}
Prims_list__Prims_string;


#define FStar_H_DEFINED
#endif /* FStar_H */
