/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-compilation -warn-error -9-11-15 -add-include "krml/internal/compat.h" -tmpdir /tmp/rdf-c-output RDF.Graph.Executable.fst
  F* version: <unknown>
  KaRaMeL version: d7a8f9ec
 */

#include "krmlinit.h"

#include "RDF_Graph_Executable.h"
#include "FStar.h"

#if defined(__GNUC__) && !(defined(_WIN32) || defined(_WIN64))
__attribute__ ((visibility ("hidden")))
#endif

void krmlinit_globals(void)
{
  RDF_Graph_Executable_rdf_graph_gc
  *buf = KRML_HOST_MALLOC(sizeof (RDF_Graph_Executable_rdf_graph_gc));
  if (buf != NULL)
    buf[0U] = ((RDF_Graph_Executable_rdf_graph_gc){ .tag = Prims_Nil });
  RDF_Graph_Executable_empty_graph = buf;
}

