/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-compilation -warn-error -9-11-15 -add-include "krml/internal/compat.h" -tmpdir /tmp/rdf-c-output RDF.Graph.Executable.fst
  F* version: <unknown>
  KaRaMeL version: d7a8f9ec
 */

#ifndef RDF_Graph_Executable_H
#define RDF_Graph_Executable_H

#include "krmllib.h"

#include "FStar.h"
#include "krml/internal/compat.h"

typedef Prims_string RDF_Graph_Executable_bnode_id;

typedef Prims_string RDF_Graph_Executable_iri;

bool RDF_Graph_Executable_list_has_colon(Prims_list__FStar_Char_char *cs);

bool RDF_Graph_Executable_string_contains_colon(Prims_string s);

bool RDF_Graph_Executable_is_iri(Prims_string s);

typedef Prims_string RDF_Graph_Executable_wf_iri;

extern Prims_string RDF_Graph_Executable_rdf_lang_string;

extern Prims_string RDF_Graph_Executable_xsd_string;

extern Prims_string RDF_Graph_Executable_xsd_integer;

extern Prims_string RDF_Graph_Executable_xsd_decimal;

extern Prims_string RDF_Graph_Executable_xsd_double;

extern Prims_string RDF_Graph_Executable_xsd_boolean;

#define FStar_Pervasives_Native_None 0
#define FStar_Pervasives_Native_Some 1

typedef uint8_t FStar_Pervasives_Native_option__Prims_string_tags;

typedef struct FStar_Pervasives_Native_option__Prims_string_s
{
  FStar_Pervasives_Native_option__Prims_string_tags tag;
  Prims_string v;
}
FStar_Pervasives_Native_option__Prims_string;

typedef struct RDF_Graph_Executable_literal_s
{
  Prims_string lexical_form;
  Prims_string datatype;
  FStar_Pervasives_Native_option__Prims_string lang_tag;
}
RDF_Graph_Executable_literal;

extern bool __eq__Prims_string(Prims_string x, Prims_string y);

bool RDF_Graph_Executable_literal_wf(RDF_Graph_Executable_literal l);

typedef RDF_Graph_Executable_literal RDF_Graph_Executable_wf_literal;

#define RDF_Graph_Executable_T_IRI 0
#define RDF_Graph_Executable_T_BNode 1
#define RDF_Graph_Executable_T_Literal 2

typedef uint8_t RDF_Graph_Executable_rdf_term_tags;

typedef struct RDF_Graph_Executable_rdf_term_s
{
  RDF_Graph_Executable_rdf_term_tags tag;
  union {
    Prims_string case_T_IRI;
    Prims_string case_T_BNode;
    RDF_Graph_Executable_literal case_T_Literal;
  }
  ;
}
RDF_Graph_Executable_rdf_term;

bool RDF_Graph_Executable_uu___is_T_IRI(RDF_Graph_Executable_rdf_term projectee);

bool RDF_Graph_Executable_uu___is_T_BNode(RDF_Graph_Executable_rdf_term projectee);

bool RDF_Graph_Executable_uu___is_T_Literal(RDF_Graph_Executable_rdf_term projectee);

#define RDF_Graph_Executable_S_IRI 0
#define RDF_Graph_Executable_S_BNode 1

typedef uint8_t RDF_Graph_Executable_subject_tags;

typedef struct RDF_Graph_Executable_subject_s
{
  RDF_Graph_Executable_subject_tags tag;
  union {
    Prims_string case_S_IRI;
    Prims_string case_S_BNode;
  }
  ;
}
RDF_Graph_Executable_subject;

bool RDF_Graph_Executable_uu___is_S_IRI(RDF_Graph_Executable_subject projectee);

bool RDF_Graph_Executable_uu___is_S_BNode(RDF_Graph_Executable_subject projectee);

bool
RDF_Graph_Executable_subject_eq(
  RDF_Graph_Executable_subject s1,
  RDF_Graph_Executable_subject s2
);

bool
RDF_Graph_Executable_literal_eq(
  RDF_Graph_Executable_literal l1,
  RDF_Graph_Executable_literal l2
);

bool
RDF_Graph_Executable_rdf_term_eq(
  RDF_Graph_Executable_rdf_term t1,
  RDF_Graph_Executable_rdf_term t2
);

typedef struct RDF_Graph_Executable_triple_s
{
  RDF_Graph_Executable_subject s;
  Prims_string p;
  RDF_Graph_Executable_rdf_term o;
}
RDF_Graph_Executable_triple;

bool
RDF_Graph_Executable_triple_eq(RDF_Graph_Executable_triple a, RDF_Graph_Executable_triple b);

typedef struct RDF_Graph_Executable_rdf_graph_gc_s RDF_Graph_Executable_rdf_graph_gc;

typedef struct RDF_Graph_Executable_rdf_graph_gc_s
{
  Prims_list__FStar_Char_char_tags tag;
  RDF_Graph_Executable_triple hd;
  RDF_Graph_Executable_rdf_graph_gc *tl;
}
RDF_Graph_Executable_rdf_graph_gc;

typedef RDF_Graph_Executable_rdf_graph_gc *RDF_Graph_Executable_rdf_graph;

extern RDF_Graph_Executable_rdf_graph_gc *RDF_Graph_Executable_empty_graph;

Prims_list__Prims_string
*RDF_Graph_Executable_graph_bnodes(RDF_Graph_Executable_rdf_graph_gc *g);

bool
RDF_Graph_Executable_mem_triple(
  RDF_Graph_Executable_triple t,
  RDF_Graph_Executable_rdf_graph_gc *g
);

RDF_Graph_Executable_rdf_graph_gc
*RDF_Graph_Executable_graph_add(
  RDF_Graph_Executable_triple t,
  RDF_Graph_Executable_rdf_graph_gc *g
);

RDF_Graph_Executable_rdf_graph_gc
*RDF_Graph_Executable_graph_remove(
  RDF_Graph_Executable_triple t,
  RDF_Graph_Executable_rdf_graph_gc *g
);

krml_checked_int_t RDF_Graph_Executable_graph_len(RDF_Graph_Executable_rdf_graph_gc *g);

RDF_Graph_Executable_rdf_graph_gc
*RDF_Graph_Executable_graph_union(
  RDF_Graph_Executable_rdf_graph_gc *g1,
  RDF_Graph_Executable_rdf_graph_gc *g2
);

RDF_Graph_Executable_rdf_graph_gc
*RDF_Graph_Executable_find_by_subject(Prims_string subj, RDF_Graph_Executable_rdf_graph_gc *g);

RDF_Graph_Executable_rdf_graph_gc
*RDF_Graph_Executable_find_by_predicate(
  Prims_string pred,
  RDF_Graph_Executable_rdf_graph_gc *g
);

bool RDF_Graph_Executable_must_escape(FStar_Char_char c);

bool RDF_Graph_Executable_is_nt_escaped_list(Prims_list__FStar_Char_char *cs);

bool RDF_Graph_Executable_is_nt_escaped(Prims_string s, krml_checked_int_t n);

typedef Prims_string RDF_Graph_Executable_var_name;

#define RDF_Graph_Executable_PT_Concrete 0
#define RDF_Graph_Executable_PT_Var 1

typedef uint8_t RDF_Graph_Executable_pattern_term_tags;

typedef struct RDF_Graph_Executable_pattern_term_s
{
  RDF_Graph_Executable_pattern_term_tags tag;
  union {
    RDF_Graph_Executable_rdf_term case_PT_Concrete;
    Prims_string case_PT_Var;
  }
  ;
}
RDF_Graph_Executable_pattern_term;

bool RDF_Graph_Executable_uu___is_PT_Concrete(RDF_Graph_Executable_pattern_term projectee);

bool RDF_Graph_Executable_uu___is_PT_Var(RDF_Graph_Executable_pattern_term projectee);

#define RDF_Graph_Executable_PS_Concrete 0
#define RDF_Graph_Executable_PS_Var 1

typedef uint8_t RDF_Graph_Executable_pattern_subject_tags;

typedef struct RDF_Graph_Executable_pattern_subject_s
{
  RDF_Graph_Executable_pattern_subject_tags tag;
  union {
    RDF_Graph_Executable_subject case_PS_Concrete;
    Prims_string case_PS_Var;
  }
  ;
}
RDF_Graph_Executable_pattern_subject;

bool RDF_Graph_Executable_uu___is_PS_Concrete(RDF_Graph_Executable_pattern_subject projectee);

bool RDF_Graph_Executable_uu___is_PS_Var(RDF_Graph_Executable_pattern_subject projectee);

typedef struct RDF_Graph_Executable_triple_pattern_s
{
  RDF_Graph_Executable_pattern_subject tp_s;
  Prims_string tp_p;
  RDF_Graph_Executable_pattern_term tp_o;
}
RDF_Graph_Executable_triple_pattern;

typedef struct K___Prims_string_RDF_Graph_Executable_rdf_term_s
{
  Prims_string fst;
  RDF_Graph_Executable_rdf_term snd;
}
K___Prims_string_RDF_Graph_Executable_rdf_term;

typedef struct Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term_s
Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term;

typedef struct Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term_s
{
  Prims_list__FStar_Char_char_tags tag;
  K___Prims_string_RDF_Graph_Executable_rdf_term hd;
  Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *tl;
}
Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term;

typedef RDF_Graph_Executable_solution_mapping_gc RDF_Graph_Executable_solution_mapping;

typedef struct RDF_Graph_Executable_bgp_gc_s RDF_Graph_Executable_bgp_gc;

typedef struct RDF_Graph_Executable_bgp_gc_s
{
  Prims_list__FStar_Char_char_tags tag;
  RDF_Graph_Executable_triple_pattern hd;
  RDF_Graph_Executable_bgp_gc *tl;
}
RDF_Graph_Executable_bgp_gc;

typedef RDF_Graph_Executable_bgp_gc *RDF_Graph_Executable_bgp;

typedef struct FStar_Pervasives_Native_option__RDF_Graph_Executable_rdf_term_s
{
  FStar_Pervasives_Native_option__Prims_string_tags tag;
  RDF_Graph_Executable_rdf_term v;
}
FStar_Pervasives_Native_option__RDF_Graph_Executable_rdf_term;

bool
RDF_Graph_Executable_pattern_subject_matches(
  RDF_Graph_Executable_pattern_subject ps,
  RDF_Graph_Executable_subject s,
  Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *mu
);

bool
RDF_Graph_Executable_pattern_term_matches(
  RDF_Graph_Executable_pattern_term pt,
  RDF_Graph_Executable_rdf_term t,
  Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *mu
);

bool
RDF_Graph_Executable_triple_pattern_matches(
  RDF_Graph_Executable_triple_pattern tp,
  RDF_Graph_Executable_triple t,
  Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *mu
);

typedef struct RDF_Graph_Executable_algebra_op_s RDF_Graph_Executable_algebra_op;

typedef struct RDF_Graph_Executable_algebra_op_s RDF_Graph_Executable_algebra_op;

typedef struct RDF_Graph_Executable_algebra_op_s RDF_Graph_Executable_algebra_op;

typedef struct RDF_Graph_Executable_algebra_op_s RDF_Graph_Executable_algebra_op;

typedef struct RDF_Graph_Executable_algebra_op_s RDF_Graph_Executable_algebra_op;

#define RDF_Graph_Executable_BGP_Op 0
#define RDF_Graph_Executable_Filter_Op 1
#define RDF_Graph_Executable_Optional_Op 2
#define RDF_Graph_Executable_Union_Op 3

typedef uint8_t RDF_Graph_Executable_algebra_op_tags;

typedef struct RDF_Graph_Executable_algebra_op_s
{
  RDF_Graph_Executable_algebra_op_tags tag;
  union {
    RDF_Graph_Executable_bgp_gc *case_BGP_Op;
    RDF_Graph_Executable_algebra_op case_Filter_Op;
    struct
    {
      RDF_Graph_Executable_algebra_op _0;
      RDF_Graph_Executable_algebra_op _1;
    }
    case_Optional_Op;
    struct
    {
      RDF_Graph_Executable_algebra_op _0;
      RDF_Graph_Executable_algebra_op _1;
    }
    case_Union_Op;
  }
  ;
}
RDF_Graph_Executable_algebra_op;

bool RDF_Graph_Executable_uu___is_BGP_Op(RDF_Graph_Executable_algebra_op projectee);

bool RDF_Graph_Executable_uu___is_Filter_Op(RDF_Graph_Executable_algebra_op projectee);

bool RDF_Graph_Executable_uu___is_Optional_Op(RDF_Graph_Executable_algebra_op projectee);

bool RDF_Graph_Executable_uu___is_Union_Op(RDF_Graph_Executable_algebra_op projectee);

typedef RDF_Graph_Executable_solution_multiset_gc RDF_Graph_Executable_solution_multiset;

#define RDF_Graph_Executable_NT_Integer 0
#define RDF_Graph_Executable_NT_Decimal 1
#define RDF_Graph_Executable_NT_Double 2
#define RDF_Graph_Executable_NT_Float 3

typedef uint8_t RDF_Graph_Executable_numeric_type;

bool RDF_Graph_Executable_uu___is_NT_Integer(RDF_Graph_Executable_numeric_type projectee);

bool RDF_Graph_Executable_uu___is_NT_Decimal(RDF_Graph_Executable_numeric_type projectee);

bool RDF_Graph_Executable_uu___is_NT_Double(RDF_Graph_Executable_numeric_type projectee);

bool RDF_Graph_Executable_uu___is_NT_Float(RDF_Graph_Executable_numeric_type projectee);

#define RDF_Graph_Executable_Eq 0
#define RDF_Graph_Executable_Ne 1
#define RDF_Graph_Executable_Lt 2
#define RDF_Graph_Executable_Gt 3
#define RDF_Graph_Executable_Le 4
#define RDF_Graph_Executable_Ge 5

typedef uint8_t RDF_Graph_Executable_comp_op;

bool RDF_Graph_Executable_uu___is_Eq(RDF_Graph_Executable_comp_op projectee);

bool RDF_Graph_Executable_uu___is_Ne(RDF_Graph_Executable_comp_op projectee);

bool RDF_Graph_Executable_uu___is_Lt(RDF_Graph_Executable_comp_op projectee);

bool RDF_Graph_Executable_uu___is_Gt(RDF_Graph_Executable_comp_op projectee);

bool RDF_Graph_Executable_uu___is_Le(RDF_Graph_Executable_comp_op projectee);

bool RDF_Graph_Executable_uu___is_Ge(RDF_Graph_Executable_comp_op projectee);

#define RDF_Graph_Executable_SV_Numeric 0
#define RDF_Graph_Executable_SV_PlainLiteral 1
#define RDF_Graph_Executable_SV_LangLiteral 2
#define RDF_Graph_Executable_SV_Iri 3
#define RDF_Graph_Executable_SV_BNode 4
#define RDF_Graph_Executable_SV_TypedLiteral 5
#define RDF_Graph_Executable_SV_Boolean 6

typedef uint8_t RDF_Graph_Executable_sparql_value_tags;

typedef struct RDF_Graph_Executable_sparql_value_s
{
  RDF_Graph_Executable_sparql_value_tags tag;
  union {
    struct
    {
      krml_checked_int_t value;
      RDF_Graph_Executable_numeric_type ntype;
    }
    case_SV_Numeric;
    Prims_string case_SV_PlainLiteral;
    struct
    {
      Prims_string lexical;
      Prims_string lang;
    }
    case_SV_LangLiteral;
    Prims_string case_SV_Iri;
    Prims_string case_SV_BNode;
    struct
    {
      Prims_string lexical;
      Prims_string datatype;
    }
    case_SV_TypedLiteral;
    bool case_SV_Boolean;
  }
  ;
}
RDF_Graph_Executable_sparql_value;

bool RDF_Graph_Executable_uu___is_SV_Numeric(RDF_Graph_Executable_sparql_value projectee);

bool RDF_Graph_Executable_uu___is_SV_PlainLiteral(RDF_Graph_Executable_sparql_value projectee);

bool RDF_Graph_Executable_uu___is_SV_LangLiteral(RDF_Graph_Executable_sparql_value projectee);

bool RDF_Graph_Executable_uu___is_SV_Iri(RDF_Graph_Executable_sparql_value projectee);

bool RDF_Graph_Executable_uu___is_SV_BNode(RDF_Graph_Executable_sparql_value projectee);

bool RDF_Graph_Executable_uu___is_SV_TypedLiteral(RDF_Graph_Executable_sparql_value projectee);

bool RDF_Graph_Executable_uu___is_SV_Boolean(RDF_Graph_Executable_sparql_value projectee);

bool RDF_Graph_Executable_string_lt(Prims_string s1, Prims_string s2);

typedef struct FStar_Pervasives_Native_option__bool_s
{
  FStar_Pervasives_Native_option__Prims_string_tags tag;
  bool v;
}
FStar_Pervasives_Native_option__bool;

FStar_Pervasives_Native_option__bool
RDF_Graph_Executable_value_compare(
  RDF_Graph_Executable_sparql_value lv,
  RDF_Graph_Executable_sparql_value rv,
  RDF_Graph_Executable_comp_op op
);

bool RDF_Graph_Executable_boolean_effective_value(RDF_Graph_Executable_sparql_value v);

typedef struct FStar_Pervasives_Native_option__RDF_Graph_Executable_sparql_value_s
{
  FStar_Pervasives_Native_option__Prims_string_tags tag;
  RDF_Graph_Executable_sparql_value v;
}
FStar_Pervasives_Native_option__RDF_Graph_Executable_sparql_value;

bool
RDF_Graph_Executable_bev_of_option(
  FStar_Pervasives_Native_option__RDF_Graph_Executable_sparql_value v
);

typedef FStar_Pervasives_Native_option__RDF_Graph_Executable_rdf_term
(*RDF_Graph_Executable_filter_expr_eval)(
  Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *x0
);

typedef struct FStar_Pervasives_Native_option__K___Prims_string_RDF_Graph_Executable_rdf_term_s
{
  FStar_Pervasives_Native_option__Prims_string_tags tag;
  K___Prims_string_RDF_Graph_Executable_rdf_term v;
}
FStar_Pervasives_Native_option__K___Prims_string_RDF_Graph_Executable_rdf_term;

FStar_Pervasives_Native_option__K___Prims_string_RDF_Graph_Executable_rdf_term
RDF_Graph_Executable_bind_eval(
  FStar_Pervasives_Native_option__RDF_Graph_Executable_rdf_term
  (*eval)(Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *x0),
  Prims_string var,
  Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *mu
);

Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term
*RDF_Graph_Executable_apply_bind(
  FStar_Pervasives_Native_option__RDF_Graph_Executable_rdf_term
  (*eval)(Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *x0),
  Prims_string var,
  Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *mu
);

krml_checked_int_t RDF_Graph_Executable_sparql_strlen(Prims_string s);

Prims_string
RDF_Graph_Executable_string_substring(
  Prims_string s,
  krml_checked_int_t i,
  krml_checked_int_t len
);

typedef struct FStar_Pervasives_Native_option__krml_checked_int_t_s
{
  FStar_Pervasives_Native_option__Prims_string_tags tag;
  krml_checked_int_t v;
}
FStar_Pervasives_Native_option__krml_checked_int_t;

Prims_string
RDF_Graph_Executable_sparql_substr(
  Prims_string s,
  krml_checked_int_t start,
  FStar_Pervasives_Native_option__krml_checked_int_t len
);

Prims_string RDF_Graph_Executable_string_to_upper(Prims_string s);

Prims_string RDF_Graph_Executable_sparql_ucase(Prims_string s);

Prims_string RDF_Graph_Executable_string_to_lower(Prims_string s);

Prims_string RDF_Graph_Executable_sparql_lcase(Prims_string s);

Prims_string RDF_Graph_Executable_sparql_concat(Prims_list__Prims_string *args);


#define RDF_Graph_Executable_H_DEFINED
#endif /* RDF_Graph_Executable_H */
