/* 
  This file was generated by KaRaMeL <https://github.com/FStarLang/karamel>
  KaRaMeL invocation: krml -skip-compilation -warn-error -9-11-15 -add-include "krml/internal/compat.h" -tmpdir /tmp/rdf-c-output RDF.Graph.Executable.fst
  F* version: <unknown>
  KaRaMeL version: d7a8f9ec
 */

#include "internal/RDF_Graph_Executable.h"

#include "FStar.h"
#include "internal/Prims.h"
#include "internal/FStar.h"

bool RDF_Graph_Executable_list_has_colon(Prims_list__FStar_Char_char *cs)
{
  if (cs->tag == Prims_Nil)
    return false;
  else if (cs->tag == Prims_Cons)
  {
    Prims_list__FStar_Char_char *rest = cs->tl;
    FStar_Char_char c = cs->hd;
    return
      FStar_Char_int_of_char(c) == (krml_checked_int_t)0x3A ||
        RDF_Graph_Executable_list_has_colon(rest);
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

bool RDF_Graph_Executable_string_contains_colon(Prims_string s)
{
  return RDF_Graph_Executable_list_has_colon(FStar_String_list_of_string(s));
}

bool RDF_Graph_Executable_is_iri(Prims_string s)
{
  return
    Prims_op_GreaterThan(FStar_String_strlen(s), (krml_checked_int_t)0) &&
      RDF_Graph_Executable_string_contains_colon(s);
}

Prims_string
RDF_Graph_Executable_rdf_lang_string = "http://www.w3.org/1999/02/22-rdf-syntax-ns#langString";

Prims_string RDF_Graph_Executable_xsd_string = "http://www.w3.org/2001/XMLSchema#string";

Prims_string RDF_Graph_Executable_xsd_integer = "http://www.w3.org/2001/XMLSchema#integer";

Prims_string RDF_Graph_Executable_xsd_decimal = "http://www.w3.org/2001/XMLSchema#decimal";

Prims_string RDF_Graph_Executable_xsd_double = "http://www.w3.org/2001/XMLSchema#double";

Prims_string RDF_Graph_Executable_xsd_boolean = "http://www.w3.org/2001/XMLSchema#boolean";

static bool __neq__Prims_string(Prims_string y, Prims_string x)
{
  return !__eq__Prims_string(x, y);
}

bool RDF_Graph_Executable_literal_wf(RDF_Graph_Executable_literal l)
{
  if (l.lang_tag.tag == FStar_Pervasives_Native_None)
    return __neq__Prims_string(l.datatype, RDF_Graph_Executable_rdf_lang_string);
  else if (l.lang_tag.tag == FStar_Pervasives_Native_Some)
    return __eq__Prims_string(l.datatype, RDF_Graph_Executable_rdf_lang_string);
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

bool RDF_Graph_Executable_uu___is_T_IRI(RDF_Graph_Executable_rdf_term projectee)
{
  if (projectee.tag == RDF_Graph_Executable_T_IRI)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_T_BNode(RDF_Graph_Executable_rdf_term projectee)
{
  if (projectee.tag == RDF_Graph_Executable_T_BNode)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_T_Literal(RDF_Graph_Executable_rdf_term projectee)
{
  if (projectee.tag == RDF_Graph_Executable_T_Literal)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_S_IRI(RDF_Graph_Executable_subject projectee)
{
  if (projectee.tag == RDF_Graph_Executable_S_IRI)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_S_BNode(RDF_Graph_Executable_subject projectee)
{
  if (projectee.tag == RDF_Graph_Executable_S_BNode)
    return true;
  else
    return false;
}

typedef struct __RDF_Graph_Executable_subject_RDF_Graph_Executable_subject_s
{
  RDF_Graph_Executable_subject fst;
  RDF_Graph_Executable_subject snd;
}
__RDF_Graph_Executable_subject_RDF_Graph_Executable_subject;

bool
RDF_Graph_Executable_subject_eq(
  RDF_Graph_Executable_subject s1,
  RDF_Graph_Executable_subject s2
)
{
  __RDF_Graph_Executable_subject_RDF_Graph_Executable_subject scrut = { .fst = s1, .snd = s2 };
  if (scrut.fst.tag == RDF_Graph_Executable_S_IRI && scrut.snd.tag == RDF_Graph_Executable_S_IRI)
  {
    Prims_string i2 = scrut.snd.case_S_IRI;
    Prims_string i1 = scrut.fst.case_S_IRI;
    return __eq__Prims_string(i1, i2);
  }
  else if
  (
    scrut.fst.tag == RDF_Graph_Executable_S_BNode && scrut.snd.tag == RDF_Graph_Executable_S_BNode
  )
  {
    Prims_string b2 = scrut.snd.case_S_BNode;
    Prims_string b1 = scrut.fst.case_S_BNode;
    return __eq__Prims_string(b1, b2);
  }
  else
    return false;
}

static bool
__eq__FStar_Pervasives_Native_option__Prims_string(
  FStar_Pervasives_Native_option__Prims_string y,
  FStar_Pervasives_Native_option__Prims_string x
)
{
  if (x.tag == FStar_Pervasives_Native_None)
    if (y.tag == FStar_Pervasives_Native_None)
      return true;
    else
      return false;
  else if (x.tag == FStar_Pervasives_Native_Some)
  {
    Prims_string x_v = x.v;
    if (y.tag == FStar_Pervasives_Native_Some)
    {
      Prims_string y_v = y.v;
      return true && __eq__Prims_string(y_v, x_v);
    }
    else
      return false;
  }
  else
    return false;
}

bool
RDF_Graph_Executable_literal_eq(
  RDF_Graph_Executable_literal l1,
  RDF_Graph_Executable_literal l2
)
{
  return
    __eq__Prims_string(l1.lexical_form, l2.lexical_form) &&
      __eq__Prims_string(l1.datatype,
        l2.datatype)
    && __eq__FStar_Pervasives_Native_option__Prims_string(l1.lang_tag, l2.lang_tag);
}

typedef struct __RDF_Graph_Executable_rdf_term_RDF_Graph_Executable_rdf_term_s
{
  RDF_Graph_Executable_rdf_term fst;
  RDF_Graph_Executable_rdf_term snd;
}
__RDF_Graph_Executable_rdf_term_RDF_Graph_Executable_rdf_term;

bool
RDF_Graph_Executable_rdf_term_eq(
  RDF_Graph_Executable_rdf_term t1,
  RDF_Graph_Executable_rdf_term t2
)
{
  __RDF_Graph_Executable_rdf_term_RDF_Graph_Executable_rdf_term scrut = { .fst = t1, .snd = t2 };
  if (scrut.fst.tag == RDF_Graph_Executable_T_IRI && scrut.snd.tag == RDF_Graph_Executable_T_IRI)
  {
    Prims_string i2 = scrut.snd.case_T_IRI;
    Prims_string i1 = scrut.fst.case_T_IRI;
    return __eq__Prims_string(i1, i2);
  }
  else if
  (
    scrut.fst.tag == RDF_Graph_Executable_T_BNode && scrut.snd.tag == RDF_Graph_Executable_T_BNode
  )
  {
    Prims_string b2 = scrut.snd.case_T_BNode;
    Prims_string b1 = scrut.fst.case_T_BNode;
    return __eq__Prims_string(b1, b2);
  }
  else if
  (
    scrut.fst.tag == RDF_Graph_Executable_T_Literal &&
      scrut.snd.tag == RDF_Graph_Executable_T_Literal
  )
  {
    RDF_Graph_Executable_literal l2 = scrut.snd.case_T_Literal;
    RDF_Graph_Executable_literal l1 = scrut.fst.case_T_Literal;
    return RDF_Graph_Executable_literal_eq(l1, l2);
  }
  else
    return false;
}

bool
RDF_Graph_Executable_triple_eq(RDF_Graph_Executable_triple a, RDF_Graph_Executable_triple b)
{
  return
    RDF_Graph_Executable_subject_eq(a.s, b.s) && __eq__Prims_string(a.p, b.p) &&
      RDF_Graph_Executable_rdf_term_eq(a.o,
        b.o);
}

RDF_Graph_Executable_rdf_graph_gc *RDF_Graph_Executable_empty_graph;

Prims_list__Prims_string
*FStar_List_Tot_Base_append__Prims_string(
  Prims_list__Prims_string *x,
  Prims_list__Prims_string *y
)
{
  if (x->tag == Prims_Nil)
    return y;
  else if (x->tag == Prims_Cons)
  {
    Prims_list__Prims_string *tl1 = x->tl;
    Prims_string a1 = x->hd;
    Prims_list__Prims_string *buf = KRML_HOST_MALLOC(sizeof (Prims_list__Prims_string));
    if (buf != NULL)
      buf[0U] =
        (
          (Prims_list__Prims_string){
            .tag = Prims_Cons,
            .hd = a1,
            .tl = FStar_List_Tot_Base_append__Prims_string(tl1, y)
          }
        );
    return buf;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static Prims_list__Prims_string
*op_At__Prims_string(Prims_list__Prims_string *x, Prims_list__Prims_string *y)
{
  return FStar_List_Tot_Base_append__Prims_string(x, y);
}

Prims_list__Prims_string
*RDF_Graph_Executable_graph_bnodes(RDF_Graph_Executable_rdf_graph_gc *g)
{
  if (g->tag == Prims_Nil)
  {
    Prims_list__Prims_string *buf = KRML_HOST_MALLOC(sizeof (Prims_list__Prims_string));
    if (buf != NULL)
      buf[0U] = ((Prims_list__Prims_string){ .tag = Prims_Nil });
    return buf;
  }
  else if (g->tag == Prims_Cons)
  {
    RDF_Graph_Executable_rdf_graph_gc *tl = g->tl;
    RDF_Graph_Executable_triple hd = g->hd;
    Prims_list__Prims_string *nodes;
    if (hd.s.tag == RDF_Graph_Executable_S_BNode)
    {
      Prims_string id = hd.s.case_S_BNode;
      Prims_list__Prims_string *buf = KRML_HOST_MALLOC(sizeof (Prims_list__Prims_string));
      if (buf != NULL)
        buf[0U] = ((Prims_list__Prims_string){ .tag = Prims_Nil });
      Prims_list__Prims_string *buf0 = KRML_HOST_MALLOC(sizeof (Prims_list__Prims_string));
      if (buf0 != NULL)
        buf0[0U] = ((Prims_list__Prims_string){ .tag = Prims_Cons, .hd = id, .tl = buf });
      nodes = buf0;
    }
    else
    {
      Prims_list__Prims_string *buf = KRML_HOST_MALLOC(sizeof (Prims_list__Prims_string));
      if (buf != NULL)
        buf[0U] = ((Prims_list__Prims_string){ .tag = Prims_Nil });
      nodes = buf;
    }
    Prims_list__Prims_string *obj_nodes;
    if (hd.o.tag == RDF_Graph_Executable_T_BNode)
    {
      Prims_string id = hd.o.case_T_BNode;
      Prims_list__Prims_string *buf = KRML_HOST_MALLOC(sizeof (Prims_list__Prims_string));
      if (buf != NULL)
        buf[0U] = ((Prims_list__Prims_string){ .tag = Prims_Nil });
      Prims_list__Prims_string *buf0 = KRML_HOST_MALLOC(sizeof (Prims_list__Prims_string));
      if (buf0 != NULL)
        buf0[0U] = ((Prims_list__Prims_string){ .tag = Prims_Cons, .hd = id, .tl = buf });
      obj_nodes = buf0;
    }
    else
    {
      Prims_list__Prims_string *buf = KRML_HOST_MALLOC(sizeof (Prims_list__Prims_string));
      if (buf != NULL)
        buf[0U] = ((Prims_list__Prims_string){ .tag = Prims_Nil });
      obj_nodes = buf;
    }
    return
      op_At__Prims_string(nodes,
        op_At__Prims_string(obj_nodes, RDF_Graph_Executable_graph_bnodes(tl)));
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

bool
RDF_Graph_Executable_mem_triple(
  RDF_Graph_Executable_triple t,
  RDF_Graph_Executable_rdf_graph_gc *g
)
{
  if (g->tag == Prims_Nil)
    return false;
  else if (g->tag == Prims_Cons)
  {
    RDF_Graph_Executable_rdf_graph_gc *tl = g->tl;
    RDF_Graph_Executable_triple hd = g->hd;
    return RDF_Graph_Executable_triple_eq(hd, t) || RDF_Graph_Executable_mem_triple(t, tl);
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

RDF_Graph_Executable_rdf_graph_gc
*FStar_List_Tot_Base_append__RDF_Graph_Executable_triple(
  RDF_Graph_Executable_rdf_graph_gc *x,
  RDF_Graph_Executable_rdf_graph_gc *y
)
{
  if (x->tag == Prims_Nil)
    return y;
  else if (x->tag == Prims_Cons)
  {
    RDF_Graph_Executable_rdf_graph_gc *tl1 = x->tl;
    RDF_Graph_Executable_triple a1 = x->hd;
    RDF_Graph_Executable_rdf_graph_gc
    *buf = KRML_HOST_MALLOC(sizeof (RDF_Graph_Executable_rdf_graph_gc));
    if (buf != NULL)
      buf[0U] =
        (
          (RDF_Graph_Executable_rdf_graph_gc){
            .tag = Prims_Cons,
            .hd = a1,
            .tl = FStar_List_Tot_Base_append__RDF_Graph_Executable_triple(tl1, y)
          }
        );
    return buf;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

static RDF_Graph_Executable_rdf_graph_gc
*op_At__RDF_Graph_Executable_triple(
  RDF_Graph_Executable_rdf_graph_gc *x,
  RDF_Graph_Executable_rdf_graph_gc *y
)
{
  return FStar_List_Tot_Base_append__RDF_Graph_Executable_triple(x, y);
}

RDF_Graph_Executable_rdf_graph_gc
*RDF_Graph_Executable_graph_add(
  RDF_Graph_Executable_triple t,
  RDF_Graph_Executable_rdf_graph_gc *g
)
{
  if (RDF_Graph_Executable_mem_triple(t, g))
    return g;
  else
  {
    RDF_Graph_Executable_rdf_graph_gc
    *buf = KRML_HOST_MALLOC(sizeof (RDF_Graph_Executable_rdf_graph_gc));
    if (buf != NULL)
      buf[0U] = ((RDF_Graph_Executable_rdf_graph_gc){ .tag = Prims_Nil });
    RDF_Graph_Executable_rdf_graph_gc
    *buf0 = KRML_HOST_MALLOC(sizeof (RDF_Graph_Executable_rdf_graph_gc));
    if (buf0 != NULL)
      buf0[0U] = ((RDF_Graph_Executable_rdf_graph_gc){ .tag = Prims_Cons, .hd = t, .tl = buf });
    return op_At__RDF_Graph_Executable_triple(g, buf0);
  }
}

RDF_Graph_Executable_rdf_graph_gc
*FStar_List_Tot_Base_filter__RDF_Graph_Executable_triple(
  bool (*f)(RDF_Graph_Executable_triple x0),
  RDF_Graph_Executable_rdf_graph_gc *uu___
)
{
  if (uu___->tag == Prims_Nil)
  {
    RDF_Graph_Executable_rdf_graph_gc
    *buf = KRML_HOST_MALLOC(sizeof (RDF_Graph_Executable_rdf_graph_gc));
    if (buf != NULL)
      buf[0U] = ((RDF_Graph_Executable_rdf_graph_gc){ .tag = Prims_Nil });
    return buf;
  }
  else if (uu___->tag == Prims_Cons)
  {
    RDF_Graph_Executable_rdf_graph_gc *tl1 = uu___->tl;
    RDF_Graph_Executable_triple hd1 = uu___->hd;
    if (f(hd1))
    {
      RDF_Graph_Executable_rdf_graph_gc
      *buf = KRML_HOST_MALLOC(sizeof (RDF_Graph_Executable_rdf_graph_gc));
      if (buf != NULL)
        buf[0U] =
          (
            (RDF_Graph_Executable_rdf_graph_gc){
              .tag = Prims_Cons,
              .hd = hd1,
              .tl = FStar_List_Tot_Base_filter__RDF_Graph_Executable_triple(f, tl1)
            }
          );
      return buf;
    }
    else
      return FStar_List_Tot_Base_filter__RDF_Graph_Executable_triple(f, tl1);
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

RDF_Graph_Executable_rdf_graph_gc
*RDF_Graph_Executable_graph_remove(
  RDF_Graph_Executable_triple t,
  RDF_Graph_Executable_rdf_graph_gc *g
)
{
  return FStar_List_Tot_Base_filter__RDF_Graph_Executable_triple((void *)0U, g);
}

krml_checked_int_t
FStar_List_Tot_Base_length__RDF_Graph_Executable_triple(
  RDF_Graph_Executable_rdf_graph_gc *uu___
)
{
  if (uu___->tag == Prims_Nil)
    return (krml_checked_int_t)0;
  else if (uu___->tag == Prims_Cons)
  {
    RDF_Graph_Executable_rdf_graph_gc *tl1 = uu___->tl;
    return
      Prims_op_Addition((krml_checked_int_t)1,
        FStar_List_Tot_Base_length__RDF_Graph_Executable_triple(tl1));
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

krml_checked_int_t RDF_Graph_Executable_graph_len(RDF_Graph_Executable_rdf_graph_gc *g)
{
  return FStar_List_Tot_Base_length__RDF_Graph_Executable_triple(g);
}

RDF_Graph_Executable_rdf_graph_gc
*RDF_Graph_Executable_graph_union(
  RDF_Graph_Executable_rdf_graph_gc *g1,
  RDF_Graph_Executable_rdf_graph_gc *g2
)
{
  if (g1->tag == Prims_Nil)
    return g2;
  else if (g1->tag == Prims_Cons)
  {
    RDF_Graph_Executable_rdf_graph_gc *tl = g1->tl;
    RDF_Graph_Executable_triple hd = g1->hd;
    return RDF_Graph_Executable_graph_union(tl, RDF_Graph_Executable_graph_add(hd, g2));
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

RDF_Graph_Executable_rdf_graph_gc
*RDF_Graph_Executable_find_by_subject(Prims_string subj, RDF_Graph_Executable_rdf_graph_gc *g)
{
  if (g->tag == Prims_Nil)
  {
    RDF_Graph_Executable_rdf_graph_gc
    *buf = KRML_HOST_MALLOC(sizeof (RDF_Graph_Executable_rdf_graph_gc));
    if (buf != NULL)
      buf[0U] = ((RDF_Graph_Executable_rdf_graph_gc){ .tag = Prims_Nil });
    return buf;
  }
  else if (g->tag == Prims_Cons)
  {
    RDF_Graph_Executable_rdf_graph_gc *tl = g->tl;
    RDF_Graph_Executable_triple hd = g->hd;
    RDF_Graph_Executable_rdf_graph_gc *rest = RDF_Graph_Executable_find_by_subject(subj, tl);
    if (hd.s.tag == RDF_Graph_Executable_S_IRI)
    {
      Prims_string i = hd.s.case_S_IRI;
      if (__eq__Prims_string(i, subj))
      {
        RDF_Graph_Executable_rdf_graph_gc
        *buf = KRML_HOST_MALLOC(sizeof (RDF_Graph_Executable_rdf_graph_gc));
        if (buf != NULL)
          buf[0U] = ((RDF_Graph_Executable_rdf_graph_gc){ .tag = Prims_Cons, .hd = hd, .tl = rest });
        return buf;
      }
      else
        return rest;
    }
    else
      return rest;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

RDF_Graph_Executable_rdf_graph_gc
*RDF_Graph_Executable_find_by_predicate(
  Prims_string pred,
  RDF_Graph_Executable_rdf_graph_gc *g
)
{
  if (g->tag == Prims_Nil)
  {
    RDF_Graph_Executable_rdf_graph_gc
    *buf = KRML_HOST_MALLOC(sizeof (RDF_Graph_Executable_rdf_graph_gc));
    if (buf != NULL)
      buf[0U] = ((RDF_Graph_Executable_rdf_graph_gc){ .tag = Prims_Nil });
    return buf;
  }
  else if (g->tag == Prims_Cons)
  {
    RDF_Graph_Executable_rdf_graph_gc *tl = g->tl;
    RDF_Graph_Executable_triple hd = g->hd;
    RDF_Graph_Executable_rdf_graph_gc *rest = RDF_Graph_Executable_find_by_predicate(pred, tl);
    if (__eq__Prims_string(hd.p, pred))
    {
      RDF_Graph_Executable_rdf_graph_gc
      *buf = KRML_HOST_MALLOC(sizeof (RDF_Graph_Executable_rdf_graph_gc));
      if (buf != NULL)
        buf[0U] = ((RDF_Graph_Executable_rdf_graph_gc){ .tag = Prims_Cons, .hd = hd, .tl = rest });
      return buf;
    }
    else
      return rest;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

bool RDF_Graph_Executable_must_escape(FStar_Char_char c)
{
  krml_checked_int_t code = FStar_Char_int_of_char(c);
  return
    code == (krml_checked_int_t)0x5C || code == (krml_checked_int_t)0x22 ||
      code == (krml_checked_int_t)0x0A
    || code == (krml_checked_int_t)0x0D
    || code == (krml_checked_int_t)0x09
    || code == (krml_checked_int_t)0x08
    || code == (krml_checked_int_t)0x0C
    || Prims_op_LessThan(code, (krml_checked_int_t)0x20);
}

bool RDF_Graph_Executable_is_nt_escaped_list(Prims_list__FStar_Char_char *cs)
{
  if (cs->tag == Prims_Nil)
    return true;
  else if (cs->tag == Prims_Cons)
  {
    Prims_list__FStar_Char_char *rest = cs->tl;
    FStar_Char_char c = cs->hd;
    krml_checked_int_t code = FStar_Char_int_of_char(c);
    if
    (
      Prims_op_LessThan(code, (krml_checked_int_t)0x20) || code == (krml_checked_int_t)0x22 ||
        code == (krml_checked_int_t)0x5C
    )
      return false;
    else
      return RDF_Graph_Executable_is_nt_escaped_list(rest);
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

bool RDF_Graph_Executable_is_nt_escaped(Prims_string s, krml_checked_int_t n)
{
  KRML_MAYBE_UNUSED_VAR(s);
  KRML_MAYBE_UNUSED_VAR(n);
  KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
    __FILE__,
    __LINE__,
    "This function was not extracted:\n([\"RDF\", \"Graph\", \"Executable\"], \"is_nt_escaped\")");
  KRML_HOST_EXIT(255U);
}

bool RDF_Graph_Executable_uu___is_PT_Concrete(RDF_Graph_Executable_pattern_term projectee)
{
  if (projectee.tag == RDF_Graph_Executable_PT_Concrete)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_PT_Var(RDF_Graph_Executable_pattern_term projectee)
{
  if (projectee.tag == RDF_Graph_Executable_PT_Var)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_PS_Concrete(RDF_Graph_Executable_pattern_subject projectee)
{
  if (projectee.tag == RDF_Graph_Executable_PS_Concrete)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_PS_Var(RDF_Graph_Executable_pattern_subject projectee)
{
  if (projectee.tag == RDF_Graph_Executable_PS_Var)
    return true;
  else
    return false;
}

FStar_Pervasives_Native_option__RDF_Graph_Executable_rdf_term
FStar_List_Tot_Base_assoc__Prims_string_RDF_Graph_Executable_rdf_term(
  Prims_string x,
  Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *uu___
)
{
  if (uu___->tag == Prims_Nil)
    return
      (
        (FStar_Pervasives_Native_option__RDF_Graph_Executable_rdf_term){
          .tag = FStar_Pervasives_Native_None
        }
      );
  else if (uu___->tag == Prims_Cons)
  {
    Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *tl1 = uu___->tl;
    RDF_Graph_Executable_rdf_term y = uu___->hd.snd;
    Prims_string x_ = uu___->hd.fst;
    if (__eq__Prims_string(x, x_))
      return
        (
          (FStar_Pervasives_Native_option__RDF_Graph_Executable_rdf_term){
            .tag = FStar_Pervasives_Native_Some,
            .v = y
          }
        );
    else
      return FStar_List_Tot_Base_assoc__Prims_string_RDF_Graph_Executable_rdf_term(x, tl1);
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

bool
RDF_Graph_Executable_pattern_subject_matches(
  RDF_Graph_Executable_pattern_subject ps,
  RDF_Graph_Executable_subject s,
  Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *mu
)
{
  if (ps.tag == RDF_Graph_Executable_PS_Concrete)
  {
    RDF_Graph_Executable_subject cs = ps.case_PS_Concrete;
    return RDF_Graph_Executable_subject_eq(cs, s);
  }
  else if (ps.tag == RDF_Graph_Executable_PS_Var)
  {
    Prims_string v = ps.case_PS_Var;
    FStar_Pervasives_Native_option__RDF_Graph_Executable_rdf_term
    scrut = FStar_List_Tot_Base_assoc__Prims_string_RDF_Graph_Executable_rdf_term(v, mu);
    if (scrut.tag == FStar_Pervasives_Native_Some && scrut.v.tag == RDF_Graph_Executable_T_IRI)
    {
      Prims_string i = scrut.v.case_T_IRI;
      return
        RDF_Graph_Executable_subject_eq(s,
          ((RDF_Graph_Executable_subject){ .tag = RDF_Graph_Executable_S_IRI, { .case_S_IRI = i } }));
    }
    else if
    (scrut.tag == FStar_Pervasives_Native_Some && scrut.v.tag == RDF_Graph_Executable_T_BNode)
    {
      Prims_string b = scrut.v.case_T_BNode;
      return
        RDF_Graph_Executable_subject_eq(s,
          (
            (RDF_Graph_Executable_subject){
              .tag = RDF_Graph_Executable_S_BNode,
              { .case_S_BNode = b }
            }
          ));
    }
    else
      return true;
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

bool
RDF_Graph_Executable_pattern_term_matches(
  RDF_Graph_Executable_pattern_term pt,
  RDF_Graph_Executable_rdf_term t,
  Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *mu
)
{
  if (pt.tag == RDF_Graph_Executable_PT_Concrete)
  {
    RDF_Graph_Executable_rdf_term ct = pt.case_PT_Concrete;
    return RDF_Graph_Executable_rdf_term_eq(ct, t);
  }
  else if (pt.tag == RDF_Graph_Executable_PT_Var)
  {
    Prims_string v = pt.case_PT_Var;
    FStar_Pervasives_Native_option__RDF_Graph_Executable_rdf_term
    scrut = FStar_List_Tot_Base_assoc__Prims_string_RDF_Graph_Executable_rdf_term(v, mu);
    if (scrut.tag == FStar_Pervasives_Native_Some)
    {
      RDF_Graph_Executable_rdf_term bound = scrut.v;
      return RDF_Graph_Executable_rdf_term_eq(bound, t);
    }
    else if (scrut.tag == FStar_Pervasives_Native_None)
      return true;
    else
    {
      KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
        __FILE__,
        __LINE__,
        "unreachable (pattern matches are exhaustive in F*)");
      KRML_HOST_EXIT(255U);
    }
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

bool
RDF_Graph_Executable_triple_pattern_matches(
  RDF_Graph_Executable_triple_pattern tp,
  RDF_Graph_Executable_triple t,
  Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *mu
)
{
  return
    RDF_Graph_Executable_pattern_subject_matches(tp.tp_s, t.s, mu) &&
      __eq__Prims_string(tp.tp_p,
        t.p)
    && RDF_Graph_Executable_pattern_term_matches(tp.tp_o, t.o, mu);
}

bool RDF_Graph_Executable_uu___is_BGP_Op(RDF_Graph_Executable_algebra_op projectee)
{
  if (projectee.tag == RDF_Graph_Executable_BGP_Op)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_Filter_Op(RDF_Graph_Executable_algebra_op projectee)
{
  if (projectee.tag == RDF_Graph_Executable_Filter_Op)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_Optional_Op(RDF_Graph_Executable_algebra_op projectee)
{
  if (projectee.tag == RDF_Graph_Executable_Optional_Op)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_Union_Op(RDF_Graph_Executable_algebra_op projectee)
{
  if (projectee.tag == RDF_Graph_Executable_Union_Op)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_NT_Integer(RDF_Graph_Executable_numeric_type projectee)
{
  switch (projectee)
  {
    case RDF_Graph_Executable_NT_Integer:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool RDF_Graph_Executable_uu___is_NT_Decimal(RDF_Graph_Executable_numeric_type projectee)
{
  switch (projectee)
  {
    case RDF_Graph_Executable_NT_Decimal:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool RDF_Graph_Executable_uu___is_NT_Double(RDF_Graph_Executable_numeric_type projectee)
{
  switch (projectee)
  {
    case RDF_Graph_Executable_NT_Double:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool RDF_Graph_Executable_uu___is_NT_Float(RDF_Graph_Executable_numeric_type projectee)
{
  switch (projectee)
  {
    case RDF_Graph_Executable_NT_Float:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool RDF_Graph_Executable_uu___is_Eq(RDF_Graph_Executable_comp_op projectee)
{
  switch (projectee)
  {
    case RDF_Graph_Executable_Eq:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool RDF_Graph_Executable_uu___is_Ne(RDF_Graph_Executable_comp_op projectee)
{
  switch (projectee)
  {
    case RDF_Graph_Executable_Ne:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool RDF_Graph_Executable_uu___is_Lt(RDF_Graph_Executable_comp_op projectee)
{
  switch (projectee)
  {
    case RDF_Graph_Executable_Lt:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool RDF_Graph_Executable_uu___is_Gt(RDF_Graph_Executable_comp_op projectee)
{
  switch (projectee)
  {
    case RDF_Graph_Executable_Gt:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool RDF_Graph_Executable_uu___is_Le(RDF_Graph_Executable_comp_op projectee)
{
  switch (projectee)
  {
    case RDF_Graph_Executable_Le:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool RDF_Graph_Executable_uu___is_Ge(RDF_Graph_Executable_comp_op projectee)
{
  switch (projectee)
  {
    case RDF_Graph_Executable_Ge:
      {
        return true;
      }
    default:
      {
        return false;
      }
  }
}

bool RDF_Graph_Executable_uu___is_SV_Numeric(RDF_Graph_Executable_sparql_value projectee)
{
  if (projectee.tag == RDF_Graph_Executable_SV_Numeric)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_SV_PlainLiteral(RDF_Graph_Executable_sparql_value projectee)
{
  if (projectee.tag == RDF_Graph_Executable_SV_PlainLiteral)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_SV_LangLiteral(RDF_Graph_Executable_sparql_value projectee)
{
  if (projectee.tag == RDF_Graph_Executable_SV_LangLiteral)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_SV_Iri(RDF_Graph_Executable_sparql_value projectee)
{
  if (projectee.tag == RDF_Graph_Executable_SV_Iri)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_SV_BNode(RDF_Graph_Executable_sparql_value projectee)
{
  if (projectee.tag == RDF_Graph_Executable_SV_BNode)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_SV_TypedLiteral(RDF_Graph_Executable_sparql_value projectee)
{
  if (projectee.tag == RDF_Graph_Executable_SV_TypedLiteral)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_uu___is_SV_Boolean(RDF_Graph_Executable_sparql_value projectee)
{
  if (projectee.tag == RDF_Graph_Executable_SV_Boolean)
    return true;
  else
    return false;
}

bool RDF_Graph_Executable_string_lt(Prims_string s1, Prims_string s2)
{
  return Prims_op_LessThan(FStar_String_compare(s1, s2), (krml_checked_int_t)0);
}

typedef struct __RDF_Graph_Executable_sparql_value_RDF_Graph_Executable_sparql_value_s
{
  RDF_Graph_Executable_sparql_value fst;
  RDF_Graph_Executable_sparql_value snd;
}
__RDF_Graph_Executable_sparql_value_RDF_Graph_Executable_sparql_value;

FStar_Pervasives_Native_option__bool
RDF_Graph_Executable_value_compare(
  RDF_Graph_Executable_sparql_value lv,
  RDF_Graph_Executable_sparql_value rv,
  RDF_Graph_Executable_comp_op op
)
{
  __RDF_Graph_Executable_sparql_value_RDF_Graph_Executable_sparql_value
  scrut = { .fst = lv, .snd = rv };
  if
  (
    scrut.fst.tag == RDF_Graph_Executable_SV_Numeric &&
      scrut.snd.tag == RDF_Graph_Executable_SV_Numeric
  )
  {
    krml_checked_int_t rn = scrut.snd.case_SV_Numeric.value;
    krml_checked_int_t ln = scrut.fst.case_SV_Numeric.value;
    bool sw;
    switch (op)
    {
      case RDF_Graph_Executable_Eq:
        {
          sw = ln == rn;
          break;
        }
      case RDF_Graph_Executable_Ne:
        {
          sw = ln != rn;
          break;
        }
      case RDF_Graph_Executable_Lt:
        {
          sw = Prims_op_LessThan(ln, rn);
          break;
        }
      case RDF_Graph_Executable_Gt:
        {
          sw = Prims_op_GreaterThan(ln, rn);
          break;
        }
      case RDF_Graph_Executable_Le:
        {
          sw = Prims_op_LessThanOrEqual(ln, rn);
          break;
        }
      case RDF_Graph_Executable_Ge:
        {
          sw = Prims_op_GreaterThanOrEqual(ln, rn);
          break;
        }
      default:
        {
          KRML_HOST_EPRINTF("KaRaMeL incomplete match at %s:%d\n", __FILE__, __LINE__);
          KRML_HOST_EXIT(253U);
        }
    }
    return
      ((FStar_Pervasives_Native_option__bool){ .tag = FStar_Pervasives_Native_Some, .v = sw });
  }
  else if
  (
    scrut.fst.tag == RDF_Graph_Executable_SV_Boolean &&
      scrut.snd.tag == RDF_Graph_Executable_SV_Boolean
  )
  {
    bool r = scrut.snd.case_SV_Boolean;
    bool l = scrut.fst.case_SV_Boolean;
    switch (op)
    {
      case RDF_Graph_Executable_Eq:
        {
          return
            (
              (FStar_Pervasives_Native_option__bool){
                .tag = FStar_Pervasives_Native_Some,
                .v = l == r
              }
            );
        }
      case RDF_Graph_Executable_Ne:
        {
          return
            (
              (FStar_Pervasives_Native_option__bool){
                .tag = FStar_Pervasives_Native_Some,
                .v = l != r
              }
            );
        }
      default:
        {
          return ((FStar_Pervasives_Native_option__bool){ .tag = FStar_Pervasives_Native_None });
        }
    }
  }
  else if
  (
    scrut.fst.tag == RDF_Graph_Executable_SV_PlainLiteral &&
      scrut.snd.tag == RDF_Graph_Executable_SV_PlainLiteral
  )
  {
    Prims_string r = scrut.snd.case_SV_PlainLiteral;
    Prims_string l = scrut.fst.case_SV_PlainLiteral;
    bool sw;
    switch (op)
    {
      case RDF_Graph_Executable_Eq:
        {
          sw = __eq__Prims_string(l, r);
          break;
        }
      case RDF_Graph_Executable_Ne:
        {
          sw = __neq__Prims_string(l, r);
          break;
        }
      case RDF_Graph_Executable_Lt:
        {
          sw = RDF_Graph_Executable_string_lt(l, r);
          break;
        }
      case RDF_Graph_Executable_Gt:
        {
          sw = RDF_Graph_Executable_string_lt(r, l);
          break;
        }
      case RDF_Graph_Executable_Le:
        {
          sw = __eq__Prims_string(l, r) || RDF_Graph_Executable_string_lt(l, r);
          break;
        }
      case RDF_Graph_Executable_Ge:
        {
          sw = __eq__Prims_string(l, r) || RDF_Graph_Executable_string_lt(r, l);
          break;
        }
      default:
        {
          KRML_HOST_EPRINTF("KaRaMeL incomplete match at %s:%d\n", __FILE__, __LINE__);
          KRML_HOST_EXIT(253U);
        }
    }
    return
      ((FStar_Pervasives_Native_option__bool){ .tag = FStar_Pervasives_Native_Some, .v = sw });
  }
  else if
  (
    scrut.fst.tag == RDF_Graph_Executable_SV_LangLiteral &&
      scrut.snd.tag == RDF_Graph_Executable_SV_LangLiteral
  )
  {
    Prims_string rlang = scrut.snd.case_SV_LangLiteral.lang;
    Prims_string rlex = scrut.snd.case_SV_LangLiteral.lexical;
    Prims_string llang = scrut.fst.case_SV_LangLiteral.lang;
    Prims_string llex = scrut.fst.case_SV_LangLiteral.lexical;
    switch (op)
    {
      case RDF_Graph_Executable_Eq:
        {
          return
            (
              (FStar_Pervasives_Native_option__bool){
                .tag = FStar_Pervasives_Native_Some,
                .v = __eq__Prims_string(llex, rlex) && __eq__Prims_string(llang, rlang)
              }
            );
        }
      case RDF_Graph_Executable_Ne:
        {
          return
            (
              (FStar_Pervasives_Native_option__bool){
                .tag = FStar_Pervasives_Native_Some,
                .v = __neq__Prims_string(llex, rlex) || __neq__Prims_string(llang, rlang)
              }
            );
        }
      default:
        {
          return ((FStar_Pervasives_Native_option__bool){ .tag = FStar_Pervasives_Native_None });
        }
    }
  }
  else if
  (scrut.fst.tag == RDF_Graph_Executable_SV_Iri && scrut.snd.tag == RDF_Graph_Executable_SV_Iri)
  {
    Prims_string r = scrut.snd.case_SV_Iri;
    Prims_string l = scrut.fst.case_SV_Iri;
    bool sw;
    switch (op)
    {
      case RDF_Graph_Executable_Eq:
        {
          sw = __eq__Prims_string(l, r);
          break;
        }
      case RDF_Graph_Executable_Ne:
        {
          sw = __neq__Prims_string(l, r);
          break;
        }
      case RDF_Graph_Executable_Lt:
        {
          sw = RDF_Graph_Executable_string_lt(l, r);
          break;
        }
      case RDF_Graph_Executable_Gt:
        {
          sw = RDF_Graph_Executable_string_lt(r, l);
          break;
        }
      case RDF_Graph_Executable_Le:
        {
          sw = __eq__Prims_string(l, r) || RDF_Graph_Executable_string_lt(l, r);
          break;
        }
      case RDF_Graph_Executable_Ge:
        {
          sw = __eq__Prims_string(l, r) || RDF_Graph_Executable_string_lt(r, l);
          break;
        }
      default:
        {
          KRML_HOST_EPRINTF("KaRaMeL incomplete match at %s:%d\n", __FILE__, __LINE__);
          KRML_HOST_EXIT(253U);
        }
    }
    return
      ((FStar_Pervasives_Native_option__bool){ .tag = FStar_Pervasives_Native_Some, .v = sw });
  }
  else if
  (
    scrut.fst.tag == RDF_Graph_Executable_SV_BNode &&
      scrut.snd.tag == RDF_Graph_Executable_SV_BNode
  )
  {
    Prims_string r = scrut.snd.case_SV_BNode;
    Prims_string l = scrut.fst.case_SV_BNode;
    switch (op)
    {
      case RDF_Graph_Executable_Eq:
        {
          return
            (
              (FStar_Pervasives_Native_option__bool){
                .tag = FStar_Pervasives_Native_Some,
                .v = __eq__Prims_string(l, r)
              }
            );
        }
      case RDF_Graph_Executable_Ne:
        {
          return
            (
              (FStar_Pervasives_Native_option__bool){
                .tag = FStar_Pervasives_Native_Some,
                .v = __neq__Prims_string(l, r)
              }
            );
        }
      default:
        {
          return ((FStar_Pervasives_Native_option__bool){ .tag = FStar_Pervasives_Native_None });
        }
    }
  }
  else if
  (
    scrut.fst.tag == RDF_Graph_Executable_SV_TypedLiteral &&
      scrut.snd.tag == RDF_Graph_Executable_SV_TypedLiteral
  )
  {
    Prims_string rdt = scrut.snd.case_SV_TypedLiteral.datatype;
    Prims_string rlex = scrut.snd.case_SV_TypedLiteral.lexical;
    Prims_string ldt = scrut.fst.case_SV_TypedLiteral.datatype;
    Prims_string llex = scrut.fst.case_SV_TypedLiteral.lexical;
    if (__eq__Prims_string(ldt, rdt))
    {
      bool sw;
      switch (op)
      {
        case RDF_Graph_Executable_Eq:
          {
            sw = __eq__Prims_string(llex, rlex);
            break;
          }
        case RDF_Graph_Executable_Ne:
          {
            sw = __neq__Prims_string(llex, rlex);
            break;
          }
        case RDF_Graph_Executable_Lt:
          {
            sw = RDF_Graph_Executable_string_lt(llex, rlex);
            break;
          }
        case RDF_Graph_Executable_Gt:
          {
            sw = RDF_Graph_Executable_string_lt(rlex, llex);
            break;
          }
        case RDF_Graph_Executable_Le:
          {
            sw = __eq__Prims_string(llex, rlex) || RDF_Graph_Executable_string_lt(llex, rlex);
            break;
          }
        case RDF_Graph_Executable_Ge:
          {
            sw = __eq__Prims_string(llex, rlex) || RDF_Graph_Executable_string_lt(rlex, llex);
            break;
          }
        default:
          {
            KRML_HOST_EPRINTF("KaRaMeL incomplete match at %s:%d\n", __FILE__, __LINE__);
            KRML_HOST_EXIT(253U);
          }
      }
      return
        ((FStar_Pervasives_Native_option__bool){ .tag = FStar_Pervasives_Native_Some, .v = sw });
    }
    else
      return ((FStar_Pervasives_Native_option__bool){ .tag = FStar_Pervasives_Native_None });
  }
  else
    return ((FStar_Pervasives_Native_option__bool){ .tag = FStar_Pervasives_Native_None });
}

bool RDF_Graph_Executable_boolean_effective_value(RDF_Graph_Executable_sparql_value v)
{
  if (v.tag == RDF_Graph_Executable_SV_Boolean)
    return v.case_SV_Boolean;
  else if (v.tag == RDF_Graph_Executable_SV_Numeric)
  {
    krml_checked_int_t n = v.case_SV_Numeric.value;
    return n != (krml_checked_int_t)0;
  }
  else if (v.tag == RDF_Graph_Executable_SV_PlainLiteral)
  {
    Prims_string s = v.case_SV_PlainLiteral;
    return Prims_op_GreaterThan(FStar_String_strlen(s), (krml_checked_int_t)0);
  }
  else if (v.tag == RDF_Graph_Executable_SV_LangLiteral)
  {
    Prims_string s = v.case_SV_LangLiteral.lexical;
    return Prims_op_GreaterThan(FStar_String_strlen(s), (krml_checked_int_t)0);
  }
  else if (v.tag == RDF_Graph_Executable_SV_Iri)
    return false;
  else if (v.tag == RDF_Graph_Executable_SV_BNode)
    return false;
  else if (v.tag == RDF_Graph_Executable_SV_TypedLiteral)
    return false;
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

bool
RDF_Graph_Executable_bev_of_option(
  FStar_Pervasives_Native_option__RDF_Graph_Executable_sparql_value v
)
{
  if (v.tag == FStar_Pervasives_Native_None)
    return false;
  else if (v.tag == FStar_Pervasives_Native_Some)
  {
    RDF_Graph_Executable_sparql_value x = v.v;
    return RDF_Graph_Executable_boolean_effective_value(x);
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

FStar_Pervasives_Native_option__K___Prims_string_RDF_Graph_Executable_rdf_term
RDF_Graph_Executable_bind_eval(
  FStar_Pervasives_Native_option__RDF_Graph_Executable_rdf_term
  (*eval)(Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *x0),
  Prims_string var,
  Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *mu
)
{
  FStar_Pervasives_Native_option__RDF_Graph_Executable_rdf_term
  scrut = FStar_List_Tot_Base_assoc__Prims_string_RDF_Graph_Executable_rdf_term(var, mu);
  if (scrut.tag == FStar_Pervasives_Native_Some)
    return
      (
        (FStar_Pervasives_Native_option__K___Prims_string_RDF_Graph_Executable_rdf_term){
          .tag = FStar_Pervasives_Native_None
        }
      );
  else if (scrut.tag == FStar_Pervasives_Native_None)
  {
    FStar_Pervasives_Native_option__RDF_Graph_Executable_rdf_term scrut = eval(mu);
    if (scrut.tag == FStar_Pervasives_Native_Some)
    {
      RDF_Graph_Executable_rdf_term term = scrut.v;
      return
        (
          (FStar_Pervasives_Native_option__K___Prims_string_RDF_Graph_Executable_rdf_term){
            .tag = FStar_Pervasives_Native_Some,
            .v = { .fst = var, .snd = term }
          }
        );
    }
    else if (scrut.tag == FStar_Pervasives_Native_None)
      return
        (
          (FStar_Pervasives_Native_option__K___Prims_string_RDF_Graph_Executable_rdf_term){
            .tag = FStar_Pervasives_Native_None
          }
        );
    else
    {
      KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
        __FILE__,
        __LINE__,
        "unreachable (pattern matches are exhaustive in F*)");
      KRML_HOST_EXIT(255U);
    }
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term
*RDF_Graph_Executable_apply_bind(
  FStar_Pervasives_Native_option__RDF_Graph_Executable_rdf_term
  (*eval)(Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *x0),
  Prims_string var,
  Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term *mu
)
{
  FStar_Pervasives_Native_option__K___Prims_string_RDF_Graph_Executable_rdf_term
  scrut = RDF_Graph_Executable_bind_eval(eval, var, mu);
  if (scrut.tag == FStar_Pervasives_Native_Some)
  {
    K___Prims_string_RDF_Graph_Executable_rdf_term pair = scrut.v;
    Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term
    *buf = KRML_HOST_MALLOC(sizeof (Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term));
    if (buf != NULL)
      buf[0U] =
        (
          (Prims_list__K___Prims_string_RDF_Graph_Executable_rdf_term){
            .tag = Prims_Cons,
            .hd = pair,
            .tl = mu
          }
        );
    return buf;
  }
  else if (scrut.tag == FStar_Pervasives_Native_None)
    return mu;
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

krml_checked_int_t RDF_Graph_Executable_sparql_strlen(Prims_string s)
{
  return FStar_String_strlen(s);
}

Prims_string
RDF_Graph_Executable_string_substring(
  Prims_string s,
  krml_checked_int_t i,
  krml_checked_int_t len
)
{
  krml_checked_int_t slen = FStar_String_strlen(s);
  if (Prims_op_GreaterThanOrEqual(i, slen))
    return "";
  else
  {
    krml_checked_int_t max_len = Prims_op_Subtraction(slen, i);
    krml_checked_int_t actual_len;
    if (Prims_op_LessThanOrEqual(len, max_len))
      actual_len = len;
    else
      actual_len = max_len;
    return FStar_String_sub(s, i, actual_len);
  }
}

Prims_string
RDF_Graph_Executable_sparql_substr(
  Prims_string s,
  krml_checked_int_t start,
  FStar_Pervasives_Native_option__krml_checked_int_t len
)
{
  krml_checked_int_t start_idx;
  if (Prims_op_GreaterThan(start, (krml_checked_int_t)0))
    start_idx = Prims_op_Subtraction(start, (krml_checked_int_t)1);
  else
    start_idx = (krml_checked_int_t)0;
  krml_checked_int_t remaining;
  if (Prims_op_GreaterThan(FStar_String_strlen(s), start_idx))
    remaining = Prims_op_Subtraction(FStar_String_strlen(s), start_idx);
  else
    remaining = (krml_checked_int_t)0;
  if (len.tag == FStar_Pervasives_Native_Some)
  {
    krml_checked_int_t n = len.v;
    return RDF_Graph_Executable_string_substring(s, start_idx, n);
  }
  else if (len.tag == FStar_Pervasives_Native_None)
    return RDF_Graph_Executable_string_substring(s, start_idx, remaining);
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

Prims_string RDF_Graph_Executable_string_to_upper(Prims_string s)
{
  return FStar_String_uppercase(s);
}

Prims_string RDF_Graph_Executable_sparql_ucase(Prims_string s)
{
  return RDF_Graph_Executable_string_to_upper(s);
}

Prims_string RDF_Graph_Executable_string_to_lower(Prims_string s)
{
  return FStar_String_lowercase(s);
}

Prims_string RDF_Graph_Executable_sparql_lcase(Prims_string s)
{
  return RDF_Graph_Executable_string_to_lower(s);
}

Prims_string RDF_Graph_Executable_sparql_concat(Prims_list__Prims_string *args)
{
  if (args->tag == Prims_Nil)
    return "";
  else if (args->tag == Prims_Cons)
  {
    Prims_list__Prims_string *tl = args->tl;
    Prims_string hd = args->hd;
    Prims_list__Prims_string *buf = KRML_HOST_MALLOC(sizeof (Prims_list__Prims_string));
    if (buf != NULL)
      buf[0U] = ((Prims_list__Prims_string){ .tag = Prims_Nil });
    Prims_list__Prims_string *buf0 = KRML_HOST_MALLOC(sizeof (Prims_list__Prims_string));
    if (buf0 != NULL)
      buf0[0U] =
        (
          (Prims_list__Prims_string){
            .tag = Prims_Cons,
            .hd = RDF_Graph_Executable_sparql_concat(tl),
            .tl = buf
          }
        );
    Prims_list__Prims_string *buf1 = KRML_HOST_MALLOC(sizeof (Prims_list__Prims_string));
    if (buf1 != NULL)
      buf1[0U] = ((Prims_list__Prims_string){ .tag = Prims_Cons, .hd = hd, .tl = buf0 });
    return FStar_String_concat("", buf1);
  }
  else
  {
    KRML_HOST_EPRINTF("KaRaMeL abort at %s:%d\n%s\n",
      __FILE__,
      __LINE__,
      "unreachable (pattern matches are exhaustive in F*)");
    KRML_HOST_EXIT(255U);
  }
}

