#!/usr/bin/env python3
"""Write tests/local/data/rdf12_sample.trig and its .nq twin.

The fixture is the wire-version-10 fixture: it holds every term shape wire
version 9 cannot store, plus the two literals that go out of line.

  * an RDF 1.2 triple term object, <<( ex:a ex:p ex:b )>>;
  * a directional language literal, "..."@ar--rtl;
  * a literal of exactly 70,000 bytes, above maxInlineLexicalBytes (65,536),
    carrying the substring "needle" so a CONTAINS filter has something to
    find inside a blob;
  * a geo:wktLiteral POLYGON above 65,536 bytes, so a geometry goes out of
    line and is therefore absent from the GBI1 index.

Deterministic: the same bytes on every run. Run from the repository root.
"""
import os

EX = "http://example.org/"
GEO = "http://www.opengis.net/ont/geosparql#"
GRAPH = EX + "g1"

# --- the 70,000-byte literal ------------------------------------------------
NEEDLE = "needle"
prefix_len = 30000
big = "a" * prefix_len + NEEDLE + "b" * (70000 - prefix_len - len(NEEDLE))
assert len(big.encode()) == 70000

# --- the large polygon ------------------------------------------------------
def ring(steps):
    pts = []
    for i in range(steps):
        pts.append((10.0 * i / steps, 0.0))
    for i in range(steps):
        pts.append((10.0, 10.0 * i / steps))
    for i in range(steps):
        pts.append((10.0 - 10.0 * i / steps, 10.0))
    for i in range(steps):
        pts.append((0.0, 10.0 - 10.0 * i / steps))
    pts.append((0.0, 0.0))
    return pts

STEPS = 1100
poly = "POLYGON((" + ", ".join(f"{x:.4f} {y:.4f}" for x, y in ring(STEPS)) + "))"
assert len(poly.encode()) > 65536, len(poly.encode())

def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')

trig = f"""# The wire-version-10 fixture. Generated by tools/make-rdf12-fixture.py;
# edit the generator, not this file.
@prefix ex: <{EX}> .
@prefix geo: <{GEO}> .

ex:s1 ex:says <<( ex:a ex:p ex:b )>> .
ex:s2 ex:label "\\u0645\\u0631\\u062D\\u0628\\u0627"@ar--rtl .

GRAPH <{GRAPH}> {{
  ex:s3 ex:big "{esc(big)}" .
  ex:s4 geo:asWKT "{esc(poly)}"^^geo:wktLiteral .
  ex:s5 ex:label "plain"@en .
}}
"""

nq = "\n".join([
    f'<{EX}s1> <{EX}says> <<( <{EX}a> <{EX}p> <{EX}b> )>> .',
    f'<{EX}s2> <{EX}label> "\\u0645\\u0631\\u062D\\u0628\\u0627"@ar--rtl .',
    f'<{EX}s3> <{EX}big> "{esc(big)}" <{GRAPH}> .',
    f'<{EX}s4> <{GEO}asWKT> "{esc(poly)}"^^<{GEO}wktLiteral> <{GRAPH}> .',
    f'<{EX}s5> <{EX}label> "plain"@en <{GRAPH}> .',
]) + "\n"

out = os.path.join("tests", "local", "data")
open(os.path.join(out, "rdf12_sample.trig"), "w").write(trig)
open(os.path.join(out, "rdf12_sample.nq"), "w").write(nq)
print(f"literal bytes={len(big.encode())} polygon bytes={len(poly.encode())}")
