#!/usr/bin/env bash
# tests/vc-di-eddsa/run.sh — run the vendored W3C vc-di-eddsa-test-suite
# (third_party/testing/vc-di-eddsa/) against bin/vc-api-shim/server.mjs,
# scoped to the eddsa-rdfc-2022 create + verify test files (task #88,
# canivc.com community-compatibility integration).
#
# Not run: 30-rdfc-interop.js, 60-jcs-interop.js, 70-data-model.js,
# 80-algorithms.js — all four import tests/vc-generator/contexts.js,
# which crashes at module-load time in this Node version
# ("DOMException [DataCloneError]: Cannot clone object of unsupported
# type" from structuredClone() on line 19) — an upstream/environment
# bug in the vendored suite's own dependency chain, not something this
# task's shim can affect. 60-jcs-interop.js is additionally out of
# scope: this shim implements eddsa-rdfc-2022 only, not eddsa-jcs-2022
# (see docs/designissues/2026-07-10-canivc-community-compat.md).
#
# Requires: `npm install` already run in third_party/testing/vc-di-eddsa
# (see that directory's PROVENANCE.md).
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SUITE_DIR="$REPO_ROOT/third_party/testing/vc-di-eddsa"
PORT="${VC_DI_EDDSA_PORT:-40447}"
RESULT_JSON="$REPO_ROOT/docs/test-results/by-suite/vc-di-eddsa.json"
MOCHA_JSON="$(mktemp)"
SHIM_LOG="$(mktemp)"

if [[ ! -d "$SUITE_DIR/node_modules" ]]; then
  echo "FAIL: $SUITE_DIR/node_modules missing — run: (cd $SUITE_DIR && npm install)"
  exit 1
fi

cleanup() {
  if [[ -n "${SHIM_PID:-}" ]] && kill -0 "$SHIM_PID" 2>/dev/null; then
    kill "$SHIM_PID" 2>/dev/null || true
    wait "$SHIM_PID" 2>/dev/null || true
  fi
  rm -f "$MOCHA_JSON" "$SHIM_LOG"
}
trap cleanup EXIT

node "$REPO_ROOT/bin/vc-api-shim/server.mjs" --port "$PORT" > "$SHIM_LOG" 2>&1 &
SHIM_PID=$!
for _ in $(seq 1 50); do
  grep -q "vc-api-shim listening on" "$SHIM_LOG" 2>/dev/null && break
  sleep 0.2
done
if ! grep -q "vc-api-shim listening on" "$SHIM_LOG" 2>/dev/null; then
  echo "FAIL: shim did not start"
  cat "$SHIM_LOG"
  exit 1
fi
ISSUER_DID="$(grep -o 'issuer=did:key:[A-Za-z0-9]*' "$SHIM_LOG" | head -1 | sed 's/issuer=//')"

cat > "$SUITE_DIR/localConfig.cjs" << EOF
/*! Generated by tests/vc-di-eddsa/run.sh (task #88). Not committed. */
const baseUrl = process.env.BASE_URL || 'http://localhost:$PORT';
module.exports = {
  settings: { enableInteropTests: false, testAllImplementations: false },
  implementations: [{
    name: 'Factoidal',
    implementation: 'Factoidal VC-API shim',
    issuers: [{
      id: '$ISSUER_DID',
      endpoint: \`\${baseUrl}/credentials/issue\`,
      supports: { vc: ['1.1', '2.0'] },
      tags: ['eddsa-rdfc-2022']
    }],
    verifiers: [{
      id: '$ISSUER_DID',
      endpoint: \`\${baseUrl}/credentials/verify\`,
      tags: ['eddsa-rdfc-2022']
    }]
  }]
};
EOF

cd "$SUITE_DIR"
MOCHA_RC=0
timeout 300 npx mocha tests/05-di-rdfc-create.js tests/15-di-rdfc-verify.js \
  --timeout 15000 --reporter json > "$MOCHA_JSON" 2>/dev/null || MOCHA_RC=$?

python3 - "$MOCHA_JSON" "$RESULT_JSON" "$MOCHA_RC" << 'PYEOF'
import json, sys, datetime

mocha_path, out_path, mocha_rc = sys.argv[1], sys.argv[2], int(sys.argv[3])

try:
    with open(mocha_path) as f:
        d = json.load(f)
except Exception as e:
    print(f"FAIL: could not parse mocha JSON reporter output: {e}")
    sys.exit(1)

stats = d["stats"]
failures = [
    {"title": f["fullTitle"], "message": (f.get("err") or {}).get("message", "")}
    for f in d["failures"]
]

result = {
    "spec": "https://w3c.github.io/vc-di-eddsa-test-suite/",
    "suite": "vc-di-eddsa (eddsa-rdfc-2022 create + verify)",
    "runner": "tests/vc-di-eddsa/run.sh",
    "retrieved_at": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    "pass": stats["passes"],
    "fail": stats["failures"],
    "skip": stats.get("pending", 0),
    "total": stats["tests"],
    "present": True,
    "not_run_files": [
        "30-rdfc-interop.js", "60-jcs-interop.js",
        "70-data-model.js", "80-algorithms.js",
    ],
    "not_run_reason": "module-load crash in the vendored suite's own tests/vc-generator/contexts.js (structuredClone DataCloneError) for 30/70/80; 60-jcs-interop.js is also out of scope (eddsa-jcs-2022 not implemented)",
    "failures": failures,
}

with open(out_path, "w") as f:
    json.dump(result, f, indent=2)
    f.write("\n")

print(f"vc-di-eddsa: {stats['passes']} pass, {stats['failures']} fail (out of {stats['tests']}) -> {out_path}")
PYEOF
